#include <unistd.h>
#include <net/if.h>
#include <stdint.h>
#include <asm/termbits.h>
#include "ioctls_list.h"
//#include <alsa/sound/asound_fm.h>
//#include <alsa/sound/emu10k1.h>
//#include <alsa/sound/hdsp.h>
//#include <alsa/sound/hdspm.h>
//#include <alsa/sound/sb16_csp.h>
//#include <alsa/sound/sscape_ioctl.h>
#include <asm-generic/ioctls.h>
//#include <asm/mce.h>
//#include <asm/msr.h>
//#include <asm/mtrr.h>
//#include <drm/drm.h>
//#include <libdrm/drm.h>
#include <linux/agpgart.h>
#include <linux/apm_bios.h>
#include <linux/arcfb.h>
#include <linux/atmarp.h>
#include <linux/atmclip.h>
#include <linux/atmdev.h>
#include <linux/atm_eni.h>
#include <linux/atm_he.h>
#include <linux/atm_idt77105.h>
#include <linux/atmlec.h>
#include <linux/atmmpc.h>
#include <linux/atm_nicstar.h>
#include <linux/atmsvc.h>
#include <linux/atm_tcp.h>
#include <linux/atm_zatm.h>
//#include <linux/aufs_type.h>
#include <linux/auto_fs4.h>
#include <linux/blkpg.h>
#include <linux/btrfs.h>
#include <linux/capi.h>
#include <linux/cciss_ioctl.h>
#include <linux/chio.h>
#include <linux/cm4000_cs.h>
#include <linux/dm-ioctl.h>
#include <linux/dn.h>
#include <linux/dvb/audio.h>
#include <linux/dvb/ca.h>
#include <linux/dvb/dmx.h>
#include <linux/dvb/frontend.h>
#include <linux/dvb/net.h>
#include <linux/dvb/osd.h>
#include <linux/dvb/video.h>
#include <linux/fb.h>
#include <linux/fd.h>
#include <linux/firewire-cdev.h>
#include <linux/fs.h>
#include <linux/gigaset_dev.h>
#include <linux/hiddev.h>
#include <linux/hidraw.h>
#include <linux/hpet.h>
#include <linux/hsi/hsi_char.h>
#include <linux/i2o-dev.h>
#include <linux/i8k.h>
#include <linux/if_tun.h>
#include <linux/input.h>
#include <linux/ipmi.h>
//#include <linux/isdn.h>
//#include <linux/isdn_ppp.h>
#include <linux/ivtvfb.h>
#include <linux/joystick.h>
#include <linux/kvm.h>
#include <linux/matroxfb.h>
#include <linux/media.h>
#include <linux/meye.h>
#include <linux/mic_ioctl.h>
#include <linux/mmtimer.h>
#include <linux/msdos_fs.h>
#include <linux/nbd.h>
//#include <linux/ncp_fs.h>
//#include <linux/nvme.h>
#include <linux/nvram.h>
#include <linux/omapfb.h>
#include <linux/perf_event.h>
#include <linux/phantom.h>
#include <linux/pktcdvd.h>
#include <linux/pmu.h>
#include <linux/ppdev.h>
#include <linux/pps.h>
#include <linux/ptp_clock.h>
#include <linux/radeonfb.h>
#include <linux/random.h>
#include <linux/reiserfs_fs.h>
#include <linux/rfkill.h>
#include <linux/rtc.h>
#include <linux/serio.h>
#include <linux/sonet.h>
#include <linux/sonypi.h>
#include <linux/spi/spidev.h>
#include <linux/suspend_ioctls.h>
#include <linux/synclink.h>
#include <linux/toshiba.h>
#include <linux/udf_fs_i.h>
#include <linux/uinput.h>
#include <linux/usbdevice_fs.h>
#include <linux/usb/functionfs.h>
#include <linux/usb/gadgetfs.h>
#include <linux/usb/g_printer.h>
#include <linux/usb/tmc.h>
#include <linux/uvcvideo.h>
#include <linux/v4l2-subdev.h>
#include <linux/vfio.h>
#include <linux/vhost.h>
#include <linux/videodev2.h>
#include <linux/watchdog.h>
#include <mtd/mtd-abi.h>
#include <mtd/ubi-user.h>
#include <net/if_ppp.h>
#include <rdma/ib_user_mad.h>
#include <sound/asound_fm.h>
#include <sound/asound.h>
#include <sound/compress_offload.h>
#include <sound/emu10k1.h>
#include <sound/firewire.h>
#include <sound/hdsp.h>
#include <sound/hdspm.h>
#include <sound/sb16_csp.h>
#include <sound/sfnt_info.h>
#include <video/sisfb.h>

const struct ioctl_entry ioctls_list[] = {
    { "TCGETS2", TCGETS2, -1, -1 }, // asm-generic/ioctls.h
    { "TCSETS2", TCSETS2, -1, -1 }, // asm-generic/ioctls.h
    { "TCSETSW2", TCSETSW2, -1, -1 }, // asm-generic/ioctls.h
    { "TCSETSF2", TCSETSF2, -1, -1 }, // asm-generic/ioctls.h
    { "TIOCGPTN", TIOCGPTN, -1, -1 }, // asm-generic/ioctls.h
    { "TIOCSPTLCK", TIOCSPTLCK, -1, -1 }, // asm-generic/ioctls.h
    { "TIOCGDEV", TIOCGDEV, -1, -1 }, // asm-generic/ioctls.h
    { "TIOCSIG", TIOCSIG, -1, -1 }, // asm-generic/ioctls.h
    { "TIOCGPKT", TIOCGPKT, -1, -1 }, // asm-generic/ioctls.h
    { "TIOCGPTLCK", TIOCGPTLCK, -1, -1 }, // asm-generic/ioctls.h
    { "TIOCGEXCL", TIOCGEXCL, -1, -1 }, // asm-generic/ioctls.h
    { "IB_USER_MAD_REGISTER_AGENT", IB_USER_MAD_REGISTER_AGENT, -1, -1 }, // rdma/ib_user_mad.h
    { "IB_USER_MAD_UNREGISTER_AGENT", IB_USER_MAD_UNREGISTER_AGENT, -1, -1 }, // rdma/ib_user_mad.h
    { "IB_USER_MAD_ENABLE_PKEY", IB_USER_MAD_ENABLE_PKEY, -1, -1 }, // rdma/ib_user_mad.h
    { "SND_SSCAPE_LOAD_BOOTB", SND_SSCAPE_LOAD_BOOTB, -1, -1 }, // alsa/sound/sscape_ioctl.h
    { "SNDRV_HDSPM_IOCTL_GET_LTC", SNDRV_HDSPM_IOCTL_GET_LTC, -1, -1 }, // alsa/sound/hdspm.h
    { "SNDRV_HDSPM_IOCTL_GET_VERSION", SNDRV_HDSPM_IOCTL_GET_VERSION, -1, -1 }, // alsa/sound/hdspm.h
    { "SNDRV_HDSPM_IOCTL_GET_MIXER", SNDRV_HDSPM_IOCTL_GET_MIXER, -1, -1 }, // alsa/sound/hdspm.h
    { "SNDRV_DM_FM_IOCTL_INFO", SNDRV_DM_FM_IOCTL_INFO, -1, -1 }, // alsa/sound/asound_fm.h
    { "SNDRV_DM_FM_IOCTL_PLAY_NOTE", SNDRV_DM_FM_IOCTL_PLAY_NOTE, -1, -1 }, // alsa/sound/asound_fm.h
    { "SNDRV_DM_FM_IOCTL_SET_VOICE", SNDRV_DM_FM_IOCTL_SET_VOICE, -1, -1 }, // alsa/sound/asound_fm.h
    { "SNDRV_DM_FM_IOCTL_SET_PARAMS", SNDRV_DM_FM_IOCTL_SET_PARAMS, -1, -1 }, // alsa/sound/asound_fm.h
    { "SNDRV_DM_FM_IOCTL_SET_MODE", SNDRV_DM_FM_IOCTL_SET_MODE, -1, -1 }, // alsa/sound/asound_fm.h
    { "SNDRV_DM_FM_IOCTL_SET_CONNECTION", SNDRV_DM_FM_IOCTL_SET_CONNECTION, -1, -1 }, // alsa/sound/asound_fm.h
    { "SNDRV_HDSP_IOCTL_GET_PEAK_RMS", SNDRV_HDSP_IOCTL_GET_PEAK_RMS, -1, -1 }, // alsa/sound/hdsp.h
    { "SNDRV_HDSP_IOCTL_GET_CONFIG_INFO", SNDRV_HDSP_IOCTL_GET_CONFIG_INFO, -1, -1 }, // alsa/sound/hdsp.h
    { "SNDRV_HDSP_IOCTL_UPLOAD_FIRMWARE", SNDRV_HDSP_IOCTL_UPLOAD_FIRMWARE, -1, -1 }, // alsa/sound/hdsp.h
    { "SNDRV_HDSP_IOCTL_GET_VERSION", SNDRV_HDSP_IOCTL_GET_VERSION, -1, -1 }, // alsa/sound/hdsp.h
    { "SNDRV_HDSP_IOCTL_GET_MIXER", SNDRV_HDSP_IOCTL_GET_MIXER, -1, -1 }, // alsa/sound/hdsp.h
    { "SNDRV_HDSP_IOCTL_GET_9632_AEB", SNDRV_HDSP_IOCTL_GET_9632_AEB, -1, -1 }, // alsa/sound/hdsp.h
    { "SNDRV_SB_CSP_IOCTL_INFO", SNDRV_SB_CSP_IOCTL_INFO, -1, -1 }, // alsa/sound/sb16_csp.h
    { "SNDRV_SB_CSP_IOCTL_LOAD_CODE", SNDRV_SB_CSP_IOCTL_LOAD_CODE, -1, -1 }, // alsa/sound/sb16_csp.h
    { "SNDRV_SB_CSP_IOCTL_UNLOAD_CODE", SNDRV_SB_CSP_IOCTL_UNLOAD_CODE, -1, -1 }, // alsa/sound/sb16_csp.h
    { "SNDRV_SB_CSP_IOCTL_START", SNDRV_SB_CSP_IOCTL_START, -1, -1 }, // alsa/sound/sb16_csp.h
    { "SNDRV_SB_CSP_IOCTL_STOP", SNDRV_SB_CSP_IOCTL_STOP, -1, -1 }, // alsa/sound/sb16_csp.h
    { "SNDRV_SB_CSP_IOCTL_PAUSE", SNDRV_SB_CSP_IOCTL_PAUSE, -1, -1 }, // alsa/sound/sb16_csp.h
    { "SNDRV_SB_CSP_IOCTL_RESTART", SNDRV_SB_CSP_IOCTL_RESTART, -1, -1 }, // alsa/sound/sb16_csp.h
    { "SNDRV_EMU10K1_IOCTL_CODE_PEEK", SNDRV_EMU10K1_IOCTL_CODE_PEEK, -1, -1 }, // alsa/sound/emu10k1.h
    { "SNDRV_EMU10K1_IOCTL_TRAM_PEEK", SNDRV_EMU10K1_IOCTL_TRAM_PEEK, -1, -1 }, // alsa/sound/emu10k1.h
    { "SNDRV_EMU10K1_IOCTL_PCM_PEEK", SNDRV_EMU10K1_IOCTL_PCM_PEEK, -1, -1 }, // alsa/sound/emu10k1.h
    { "MEMGETINFO", MEMGETINFO, -1, -1 }, // mtd/mtd-abi.h
    { "MEMERASE", MEMERASE, -1, -1 }, // mtd/mtd-abi.h
    { "MEMWRITEOOB", MEMWRITEOOB, -1, -1 }, // mtd/mtd-abi.h
    { "MEMREADOOB", MEMREADOOB, -1, -1 }, // mtd/mtd-abi.h
    { "MEMLOCK", MEMLOCK, -1, -1 }, // mtd/mtd-abi.h
    { "MEMUNLOCK", MEMUNLOCK, -1, -1 }, // mtd/mtd-abi.h
    { "MEMGETREGIONCOUNT", MEMGETREGIONCOUNT, -1, -1 }, // mtd/mtd-abi.h
    { "MEMGETREGIONINFO", MEMGETREGIONINFO, -1, -1 }, // mtd/mtd-abi.h
    { "MEMGETOOBSEL", MEMGETOOBSEL, -1, -1 }, // mtd/mtd-abi.h
    { "MEMGETBADBLOCK", MEMGETBADBLOCK, -1, -1 }, // mtd/mtd-abi.h
    { "MEMSETBADBLOCK", MEMSETBADBLOCK, -1, -1 }, // mtd/mtd-abi.h
    { "OTPSELECT", OTPSELECT, -1, -1 }, // mtd/mtd-abi.h
    { "OTPGETREGIONCOUNT", OTPGETREGIONCOUNT, -1, -1 }, // mtd/mtd-abi.h
    { "OTPGETREGIONINFO", OTPGETREGIONINFO, -1, -1 }, // mtd/mtd-abi.h
    { "OTPLOCK", OTPLOCK, -1, -1 }, // mtd/mtd-abi.h
    { "ECCGETLAYOUT", ECCGETLAYOUT, -1, -1 }, // mtd/mtd-abi.h
    { "ECCGETSTATS", ECCGETSTATS, -1, -1 }, // mtd/mtd-abi.h
    { "MTDFILEMODE", MTDFILEMODE, -1, -1 }, // mtd/mtd-abi.h
    { "MEMERASE64", MEMERASE64, -1, -1 }, // mtd/mtd-abi.h
    { "MEMWRITEOOB64", MEMWRITEOOB64, -1, -1 }, // mtd/mtd-abi.h
    { "MEMREADOOB64", MEMREADOOB64, -1, -1 }, // mtd/mtd-abi.h
    { "MEMISLOCKED", MEMISLOCKED, -1, -1 }, // mtd/mtd-abi.h
    { "MEMWRITE", MEMWRITE, -1, -1 }, // mtd/mtd-abi.h
    { "UBI_IOCMKVOL", UBI_IOCMKVOL, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCRMVOL", UBI_IOCRMVOL, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCRSVOL", UBI_IOCRSVOL, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCRNVOL", UBI_IOCRNVOL, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCATT", UBI_IOCATT, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCDET", UBI_IOCDET, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCVOLUP", UBI_IOCVOLUP, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCEBER", UBI_IOCEBER, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCEBCH", UBI_IOCEBCH, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCEBMAP", UBI_IOCEBMAP, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCEBUNMAP", UBI_IOCEBUNMAP, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCEBISMAP", UBI_IOCEBISMAP, -1, -1 }, // mtd/ubi-user.h
    { "UBI_IOCSETVOLPROP", UBI_IOCSETVOLPROP, -1, -1 }, // mtd/ubi-user.h
    { "SNDRV_HDSPM_IOCTL_GET_LTC", SNDRV_HDSPM_IOCTL_GET_LTC, -1, -1 }, // sound/hdspm.h
    { "SNDRV_HDSPM_IOCTL_GET_VERSION", SNDRV_HDSPM_IOCTL_GET_VERSION, -1, -1 }, // sound/hdspm.h
    { "SNDRV_HDSPM_IOCTL_GET_MIXER", SNDRV_HDSPM_IOCTL_GET_MIXER, -1, -1 }, // sound/hdspm.h
    { "SNDRV_DM_FM_IOCTL_INFO", SNDRV_DM_FM_IOCTL_INFO, -1, -1 }, // sound/asound_fm.h
    { "SNDRV_DM_FM_IOCTL_PLAY_NOTE", SNDRV_DM_FM_IOCTL_PLAY_NOTE, -1, -1 }, // sound/asound_fm.h
    { "SNDRV_DM_FM_IOCTL_SET_VOICE", SNDRV_DM_FM_IOCTL_SET_VOICE, -1, -1 }, // sound/asound_fm.h
    { "SNDRV_DM_FM_IOCTL_SET_PARAMS", SNDRV_DM_FM_IOCTL_SET_PARAMS, -1, -1 }, // sound/asound_fm.h
    { "SNDRV_DM_FM_IOCTL_SET_MODE", SNDRV_DM_FM_IOCTL_SET_MODE, -1, -1 }, // sound/asound_fm.h
    { "SNDRV_DM_FM_IOCTL_SET_CONNECTION", SNDRV_DM_FM_IOCTL_SET_CONNECTION, -1, -1 }, // sound/asound_fm.h
    { "SNDRV_FIREWIRE_IOCTL_GET_INFO", SNDRV_FIREWIRE_IOCTL_GET_INFO, -1, -1 }, // sound/firewire.h
    { "SNDRV_FIREWIRE_IOCTL_LOCK", SNDRV_FIREWIRE_IOCTL_LOCK, -1, -1 }, // sound/firewire.h
    { "SNDRV_FIREWIRE_IOCTL_UNLOCK", SNDRV_FIREWIRE_IOCTL_UNLOCK, -1, -1 }, // sound/firewire.h
    { "SNDRV_HDSP_IOCTL_GET_PEAK_RMS", SNDRV_HDSP_IOCTL_GET_PEAK_RMS, -1, -1 }, // sound/hdsp.h
    { "SNDRV_HDSP_IOCTL_GET_CONFIG_INFO", SNDRV_HDSP_IOCTL_GET_CONFIG_INFO, -1, -1 }, // sound/hdsp.h
    { "SNDRV_HDSP_IOCTL_UPLOAD_FIRMWARE", SNDRV_HDSP_IOCTL_UPLOAD_FIRMWARE, -1, -1 }, // sound/hdsp.h
    { "SNDRV_HDSP_IOCTL_GET_VERSION", SNDRV_HDSP_IOCTL_GET_VERSION, -1, -1 }, // sound/hdsp.h
    { "SNDRV_HDSP_IOCTL_GET_MIXER", SNDRV_HDSP_IOCTL_GET_MIXER, -1, -1 }, // sound/hdsp.h
    { "SNDRV_HDSP_IOCTL_GET_9632_AEB", SNDRV_HDSP_IOCTL_GET_9632_AEB, -1, -1 }, // sound/hdsp.h
    { "SNDRV_HWDEP_IOCTL_DSP_STATUS", SNDRV_HWDEP_IOCTL_DSP_STATUS, -1, -1 }, // sound/asound.h
    { "SNDRV_HWDEP_IOCTL_DSP_LOAD", SNDRV_HWDEP_IOCTL_DSP_LOAD, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_PVERSION", SNDRV_PCM_IOCTL_PVERSION, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_INFO", SNDRV_PCM_IOCTL_INFO, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_TSTAMP", SNDRV_PCM_IOCTL_TSTAMP, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_TTSTAMP", SNDRV_PCM_IOCTL_TTSTAMP, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_HW_REFINE", SNDRV_PCM_IOCTL_HW_REFINE, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_HW_PARAMS", SNDRV_PCM_IOCTL_HW_PARAMS, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_HW_FREE", SNDRV_PCM_IOCTL_HW_FREE, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_SW_PARAMS", SNDRV_PCM_IOCTL_SW_PARAMS, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_STATUS", SNDRV_PCM_IOCTL_STATUS, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_DELAY", SNDRV_PCM_IOCTL_DELAY, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_HWSYNC", SNDRV_PCM_IOCTL_HWSYNC, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_SYNC_PTR", SNDRV_PCM_IOCTL_SYNC_PTR, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_CHANNEL_INFO", SNDRV_PCM_IOCTL_CHANNEL_INFO, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_PREPARE", SNDRV_PCM_IOCTL_PREPARE, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_RESET", SNDRV_PCM_IOCTL_RESET, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_START", SNDRV_PCM_IOCTL_START, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_DROP", SNDRV_PCM_IOCTL_DROP, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_DRAIN", SNDRV_PCM_IOCTL_DRAIN, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_PAUSE", SNDRV_PCM_IOCTL_PAUSE, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_REWIND", SNDRV_PCM_IOCTL_REWIND, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_RESUME", SNDRV_PCM_IOCTL_RESUME, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_XRUN", SNDRV_PCM_IOCTL_XRUN, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_FORWARD", SNDRV_PCM_IOCTL_FORWARD, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_WRITEI_FRAMES", SNDRV_PCM_IOCTL_WRITEI_FRAMES, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_READI_FRAMES", SNDRV_PCM_IOCTL_READI_FRAMES, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_WRITEN_FRAMES", SNDRV_PCM_IOCTL_WRITEN_FRAMES, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_READN_FRAMES", SNDRV_PCM_IOCTL_READN_FRAMES, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_LINK", SNDRV_PCM_IOCTL_LINK, -1, -1 }, // sound/asound.h
    { "SNDRV_PCM_IOCTL_UNLINK", SNDRV_PCM_IOCTL_UNLINK, -1, -1 }, // sound/asound.h
    { "SNDRV_RAWMIDI_IOCTL_PVERSION", SNDRV_RAWMIDI_IOCTL_PVERSION, -1, -1 }, // sound/asound.h
    { "SNDRV_RAWMIDI_IOCTL_INFO", SNDRV_RAWMIDI_IOCTL_INFO, -1, -1 }, // sound/asound.h
    { "SNDRV_RAWMIDI_IOCTL_PARAMS", SNDRV_RAWMIDI_IOCTL_PARAMS, -1, -1 }, // sound/asound.h
    { "SNDRV_RAWMIDI_IOCTL_STATUS", SNDRV_RAWMIDI_IOCTL_STATUS, -1, -1 }, // sound/asound.h
    { "SNDRV_RAWMIDI_IOCTL_DROP", SNDRV_RAWMIDI_IOCTL_DROP, -1, -1 }, // sound/asound.h
    { "SNDRV_RAWMIDI_IOCTL_DRAIN", SNDRV_RAWMIDI_IOCTL_DRAIN, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_PVERSION", SNDRV_TIMER_IOCTL_PVERSION, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_NEXT_DEVICE", SNDRV_TIMER_IOCTL_NEXT_DEVICE, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_TREAD", SNDRV_TIMER_IOCTL_TREAD, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_GINFO", SNDRV_TIMER_IOCTL_GINFO, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_GPARAMS", SNDRV_TIMER_IOCTL_GPARAMS, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_GSTATUS", SNDRV_TIMER_IOCTL_GSTATUS, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_SELECT", SNDRV_TIMER_IOCTL_SELECT, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_INFO", SNDRV_TIMER_IOCTL_INFO, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_PARAMS", SNDRV_TIMER_IOCTL_PARAMS, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_STATUS", SNDRV_TIMER_IOCTL_STATUS, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_START", SNDRV_TIMER_IOCTL_START, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_STOP", SNDRV_TIMER_IOCTL_STOP, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_CONTINUE", SNDRV_TIMER_IOCTL_CONTINUE, -1, -1 }, // sound/asound.h
    { "SNDRV_TIMER_IOCTL_PAUSE", SNDRV_TIMER_IOCTL_PAUSE, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_PVERSION", SNDRV_CTL_IOCTL_PVERSION, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_CARD_INFO", SNDRV_CTL_IOCTL_CARD_INFO, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_ELEM_LIST", SNDRV_CTL_IOCTL_ELEM_LIST, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_ELEM_INFO", SNDRV_CTL_IOCTL_ELEM_INFO, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_ELEM_READ", SNDRV_CTL_IOCTL_ELEM_READ, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_ELEM_WRITE", SNDRV_CTL_IOCTL_ELEM_WRITE, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_ELEM_LOCK", SNDRV_CTL_IOCTL_ELEM_LOCK, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_ELEM_UNLOCK", SNDRV_CTL_IOCTL_ELEM_UNLOCK, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_SUBSCRIBE_EVENTS", SNDRV_CTL_IOCTL_SUBSCRIBE_EVENTS, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_ELEM_ADD", SNDRV_CTL_IOCTL_ELEM_ADD, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_ELEM_REPLACE", SNDRV_CTL_IOCTL_ELEM_REPLACE, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_ELEM_REMOVE", SNDRV_CTL_IOCTL_ELEM_REMOVE, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_TLV_READ", SNDRV_CTL_IOCTL_TLV_READ, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_TLV_WRITE", SNDRV_CTL_IOCTL_TLV_WRITE, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_TLV_COMMAND", SNDRV_CTL_IOCTL_TLV_COMMAND, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_HWDEP_NEXT_DEVICE", SNDRV_CTL_IOCTL_HWDEP_NEXT_DEVICE, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_HWDEP_INFO", SNDRV_CTL_IOCTL_HWDEP_INFO, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_PCM_NEXT_DEVICE", SNDRV_CTL_IOCTL_PCM_NEXT_DEVICE, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_PCM_INFO", SNDRV_CTL_IOCTL_PCM_INFO, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_PCM_PREFER_SUBDEVICE", SNDRV_CTL_IOCTL_PCM_PREFER_SUBDEVICE, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_RAWMIDI_NEXT_DEVICE", SNDRV_CTL_IOCTL_RAWMIDI_NEXT_DEVICE, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_RAWMIDI_INFO", SNDRV_CTL_IOCTL_RAWMIDI_INFO, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_RAWMIDI_PREFER_SUBDEVICE", SNDRV_CTL_IOCTL_RAWMIDI_PREFER_SUBDEVICE, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_POWER", SNDRV_CTL_IOCTL_POWER, -1, -1 }, // sound/asound.h
    { "SNDRV_CTL_IOCTL_POWER_STATE", SNDRV_CTL_IOCTL_POWER_STATE, -1, -1 }, // sound/asound.h
    { "SNDRV_COMPRESS_IOCTL_VERSION", SNDRV_COMPRESS_IOCTL_VERSION, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_GET_CAPS", SNDRV_COMPRESS_GET_CAPS, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_GET_CODEC_CAPS", SNDRV_COMPRESS_GET_CODEC_CAPS, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_SET_PARAMS", SNDRV_COMPRESS_SET_PARAMS, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_GET_PARAMS", SNDRV_COMPRESS_GET_PARAMS, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_SET_METADATA", SNDRV_COMPRESS_SET_METADATA, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_GET_METADATA", SNDRV_COMPRESS_GET_METADATA, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_TSTAMP", SNDRV_COMPRESS_TSTAMP, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_AVAIL", SNDRV_COMPRESS_AVAIL, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_PAUSE", SNDRV_COMPRESS_PAUSE, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_RESUME", SNDRV_COMPRESS_RESUME, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_START", SNDRV_COMPRESS_START, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_STOP", SNDRV_COMPRESS_STOP, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_DRAIN", SNDRV_COMPRESS_DRAIN, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_NEXT_TRACK", SNDRV_COMPRESS_NEXT_TRACK, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_COMPRESS_PARTIAL_DRAIN", SNDRV_COMPRESS_PARTIAL_DRAIN, -1, -1 }, // sound/compress_offload.h
    { "SNDRV_SB_CSP_IOCTL_INFO", SNDRV_SB_CSP_IOCTL_INFO, -1, -1 }, // sound/sb16_csp.h
    { "SNDRV_SB_CSP_IOCTL_UNLOAD_CODE", SNDRV_SB_CSP_IOCTL_UNLOAD_CODE, -1, -1 }, // sound/sb16_csp.h
    { "SNDRV_SB_CSP_IOCTL_START", SNDRV_SB_CSP_IOCTL_START, -1, -1 }, // sound/sb16_csp.h
    { "SNDRV_SB_CSP_IOCTL_STOP", SNDRV_SB_CSP_IOCTL_STOP, -1, -1 }, // sound/sb16_csp.h
    { "SNDRV_SB_CSP_IOCTL_PAUSE", SNDRV_SB_CSP_IOCTL_PAUSE, -1, -1 }, // sound/sb16_csp.h
    { "SNDRV_SB_CSP_IOCTL_RESTART", SNDRV_SB_CSP_IOCTL_RESTART, -1, -1 }, // sound/sb16_csp.h
    { "SNDRV_EMU10K1_IOCTL_CODE_PEEK", SNDRV_EMU10K1_IOCTL_CODE_PEEK, -1, -1 }, // sound/emu10k1.h
    { "SNDRV_EMU10K1_IOCTL_TRAM_PEEK", SNDRV_EMU10K1_IOCTL_TRAM_PEEK, -1, -1 }, // sound/emu10k1.h
    { "SNDRV_EMU10K1_IOCTL_PCM_PEEK", SNDRV_EMU10K1_IOCTL_PCM_PEEK, -1, -1 }, // sound/emu10k1.h
    { "SNDRV_EMUX_IOCTL_VERSION", SNDRV_EMUX_IOCTL_VERSION, -1, -1 }, // sound/sfnt_info.h
    { "SNDRV_EMUX_IOCTL_LOAD_PATCH", SNDRV_EMUX_IOCTL_LOAD_PATCH, -1, -1 }, // sound/sfnt_info.h
    { "SNDRV_EMUX_IOCTL_RESET_SAMPLES", SNDRV_EMUX_IOCTL_RESET_SAMPLES, -1, -1 }, // sound/sfnt_info.h
    { "SNDRV_EMUX_IOCTL_REMOVE_LAST_SAMPLES", SNDRV_EMUX_IOCTL_REMOVE_LAST_SAMPLES, -1, -1 }, // sound/sfnt_info.h
    { "SNDRV_EMUX_IOCTL_MEM_AVAIL", SNDRV_EMUX_IOCTL_MEM_AVAIL, -1, -1 }, // sound/sfnt_info.h
    { "SNDRV_EMUX_IOCTL_MISC_MODE", SNDRV_EMUX_IOCTL_MISC_MODE, -1, -1 }, // sound/sfnt_info.h
    { "PPPIOCGFLAGS", PPPIOCGFLAGS, -1, -1 }, // net/if_ppp.h
    { "PPPIOCSFLAGS", PPPIOCSFLAGS, -1, -1 }, // net/if_ppp.h
    { "PPPIOCGASYNCMAP", PPPIOCGASYNCMAP, -1, -1 }, // net/if_ppp.h
    { "PPPIOCSASYNCMAP", PPPIOCSASYNCMAP, -1, -1 }, // net/if_ppp.h
    { "PPPIOCGUNIT", PPPIOCGUNIT, -1, -1 }, // net/if_ppp.h
    { "PPPIOCGRASYNCMAP", PPPIOCGRASYNCMAP, -1, -1 }, // net/if_ppp.h
    { "PPPIOCSRASYNCMAP", PPPIOCSRASYNCMAP, -1, -1 }, // net/if_ppp.h
    { "PPPIOCGMRU", PPPIOCGMRU, -1, -1 }, // net/if_ppp.h
    { "PPPIOCSMRU", PPPIOCSMRU, -1, -1 }, // net/if_ppp.h
    { "PPPIOCSMAXCID", PPPIOCSMAXCID, -1, -1 }, // net/if_ppp.h
    { "PPPIOCGXASYNCMAP", PPPIOCGXASYNCMAP, -1, -1 }, // net/if_ppp.h
    { "PPPIOCSXASYNCMAP", PPPIOCSXASYNCMAP, -1, -1 }, // net/if_ppp.h
    { "PPPIOCXFERUNIT", PPPIOCXFERUNIT, -1, -1 }, // net/if_ppp.h
    { "PPPIOCSCOMPRESS", PPPIOCSCOMPRESS, -1, -1 }, // net/if_ppp.h
    { "PPPIOCGNPMODE", PPPIOCGNPMODE, -1, -1 }, // net/if_ppp.h
    { "PPPIOCSNPMODE", PPPIOCSNPMODE, -1, -1 }, // net/if_ppp.h
    { "PPPIOCGDEBUG", PPPIOCGDEBUG, -1, -1 }, // net/if_ppp.h
    { "PPPIOCSDEBUG", PPPIOCSDEBUG, -1, -1 }, // net/if_ppp.h
    { "PPPIOCGIDLE", PPPIOCGIDLE, -1, -1 }, // net/if_ppp.h
    { "ATM_GETLINKRATE", ATM_GETLINKRATE, -1, -1 }, // linux/atmdev.h
    { "ATM_GETNAMES", ATM_GETNAMES, -1, -1 }, // linux/atmdev.h
    { "ATM_GETTYPE", ATM_GETTYPE, -1, -1 }, // linux/atmdev.h
    { "ATM_GETESI", ATM_GETESI, -1, -1 }, // linux/atmdev.h
    { "ATM_GETADDR", ATM_GETADDR, -1, -1 }, // linux/atmdev.h
    { "ATM_RSTADDR", ATM_RSTADDR, -1, -1 }, // linux/atmdev.h
    { "ATM_ADDADDR", ATM_ADDADDR, -1, -1 }, // linux/atmdev.h
    { "ATM_DELADDR", ATM_DELADDR, -1, -1 }, // linux/atmdev.h
    { "ATM_GETCIRANGE", ATM_GETCIRANGE, -1, -1 }, // linux/atmdev.h
    { "ATM_SETCIRANGE", ATM_SETCIRANGE, -1, -1 }, // linux/atmdev.h
    { "ATM_SETESI", ATM_SETESI, -1, -1 }, // linux/atmdev.h
    { "ATM_SETESIF", ATM_SETESIF, -1, -1 }, // linux/atmdev.h
    { "ATM_ADDLECSADDR", ATM_ADDLECSADDR, -1, -1 }, // linux/atmdev.h
    { "ATM_DELLECSADDR", ATM_DELLECSADDR, -1, -1 }, // linux/atmdev.h
    { "ATM_GETLECSADDR", ATM_GETLECSADDR, -1, -1 }, // linux/atmdev.h
    { "ATM_GETSTAT", ATM_GETSTAT, -1, -1 }, // linux/atmdev.h
    { "ATM_GETSTATZ", ATM_GETSTATZ, -1, -1 }, // linux/atmdev.h
    { "ATM_GETLOOP", ATM_GETLOOP, -1, -1 }, // linux/atmdev.h
    { "ATM_SETLOOP", ATM_SETLOOP, -1, -1 }, // linux/atmdev.h
    { "ATM_QUERYLOOP", ATM_QUERYLOOP, -1, -1 }, // linux/atmdev.h
    { "ATM_SETSC", ATM_SETSC, -1, -1 }, // linux/atmdev.h
    { "ATM_SETBACKEND", ATM_SETBACKEND, -1, -1 }, // linux/atmdev.h
    { "ATM_NEWBACKENDIF", ATM_NEWBACKENDIF, -1, -1 }, // linux/atmdev.h
    { "ATM_ADDPARTY", ATM_ADDPARTY, -1, -1 }, // linux/atmdev.h
    { "ATM_DROPPARTY", ATM_DROPPARTY, -1, -1 }, // linux/atmdev.h
    { "SNAPSHOT_FREEZE", SNAPSHOT_FREEZE, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_UNFREEZE", SNAPSHOT_UNFREEZE, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_ATOMIC_RESTORE", SNAPSHOT_ATOMIC_RESTORE, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_FREE", SNAPSHOT_FREE, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_FREE_SWAP_PAGES", SNAPSHOT_FREE_SWAP_PAGES, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_S2RAM", SNAPSHOT_S2RAM, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_SET_SWAP_AREA", SNAPSHOT_SET_SWAP_AREA, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_GET_IMAGE_SIZE", SNAPSHOT_GET_IMAGE_SIZE, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_PLATFORM_SUPPORT", SNAPSHOT_PLATFORM_SUPPORT, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_POWER_OFF", SNAPSHOT_POWER_OFF, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_CREATE_IMAGE", SNAPSHOT_CREATE_IMAGE, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_PREF_IMAGE_SIZE", SNAPSHOT_PREF_IMAGE_SIZE, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_AVAIL_SWAP_SIZE", SNAPSHOT_AVAIL_SWAP_SIZE, -1, -1 }, // linux/suspend_ioctls.h
    { "SNAPSHOT_ALLOC_SWAP_PAGE", SNAPSHOT_ALLOC_SWAP_PAGE, -1, -1 }, // linux/suspend_ioctls.h
    { "MGSL_IOCSPARAMS", MGSL_IOCSPARAMS, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCGPARAMS", MGSL_IOCGPARAMS, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCSTXIDLE", MGSL_IOCSTXIDLE, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCGTXIDLE", MGSL_IOCGTXIDLE, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCTXENABLE", MGSL_IOCTXENABLE, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCRXENABLE", MGSL_IOCRXENABLE, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCTXABORT", MGSL_IOCTXABORT, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCGSTATS", MGSL_IOCGSTATS, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCWAITEVENT", MGSL_IOCWAITEVENT, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCCLRMODCOUNT", MGSL_IOCCLRMODCOUNT, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCLOOPTXDONE", MGSL_IOCLOOPTXDONE, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCSIF", MGSL_IOCSIF, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCGIF", MGSL_IOCGIF, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCSGPIO", MGSL_IOCSGPIO, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCGGPIO", MGSL_IOCGGPIO, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCWAITGPIO", MGSL_IOCWAITGPIO, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCSXSYNC", MGSL_IOCSXSYNC, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCGXSYNC", MGSL_IOCGXSYNC, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCSXCTRL", MGSL_IOCSXCTRL, -1, -1 }, // linux/synclink.h
    { "MGSL_IOCGXCTRL", MGSL_IOCGXCTRL, -1, -1 }, // linux/synclink.h
    { "MEDIA_IOC_DEVICE_INFO", MEDIA_IOC_DEVICE_INFO, -1, -1 }, // linux/media.h
    { "MEDIA_IOC_ENUM_ENTITIES", MEDIA_IOC_ENUM_ENTITIES, -1, -1 }, // linux/media.h
    { "MEDIA_IOC_ENUM_LINKS", MEDIA_IOC_ENUM_LINKS, -1, -1 }, // linux/media.h
    { "MEDIA_IOC_SETUP_LINK", MEDIA_IOC_SETUP_LINK, -1, -1 }, // linux/media.h
    { "FBIO_RADEON_GET_MIRROR", FBIO_RADEON_GET_MIRROR, -1, -1 }, // linux/radeonfb.h
    { "FBIO_RADEON_SET_MIRROR", FBIO_RADEON_SET_MIRROR, -1, -1 }, // linux/radeonfb.h
    { "CA_RESET", CA_RESET, -1, -1 }, // linux/dvb/ca.h
    { "CA_GET_CAP", CA_GET_CAP, -1, -1 }, // linux/dvb/ca.h
    { "CA_GET_SLOT_INFO", CA_GET_SLOT_INFO, -1, -1 }, // linux/dvb/ca.h
    { "CA_GET_DESCR_INFO", CA_GET_DESCR_INFO, -1, -1 }, // linux/dvb/ca.h
    { "CA_GET_MSG", CA_GET_MSG, -1, -1 }, // linux/dvb/ca.h
    { "CA_SEND_MSG", CA_SEND_MSG, -1, -1 }, // linux/dvb/ca.h
    { "CA_SET_DESCR", CA_SET_DESCR, -1, -1 }, // linux/dvb/ca.h
    { "CA_SET_PID", CA_SET_PID, -1, -1 }, // linux/dvb/ca.h
    { "VIDEO_STOP", VIDEO_STOP, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_PLAY", VIDEO_PLAY, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_FREEZE", VIDEO_FREEZE, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_CONTINUE", VIDEO_CONTINUE, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SELECT_SOURCE", VIDEO_SELECT_SOURCE, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SET_BLANK", VIDEO_SET_BLANK, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_GET_STATUS", VIDEO_GET_STATUS, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_GET_EVENT", VIDEO_GET_EVENT, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SET_DISPLAY_FORMAT", VIDEO_SET_DISPLAY_FORMAT, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_STILLPICTURE", VIDEO_STILLPICTURE, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_FAST_FORWARD", VIDEO_FAST_FORWARD, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SLOWMOTION", VIDEO_SLOWMOTION, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_GET_CAPABILITIES", VIDEO_GET_CAPABILITIES, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_CLEAR_BUFFER", VIDEO_CLEAR_BUFFER, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SET_ID", VIDEO_SET_ID, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SET_STREAMTYPE", VIDEO_SET_STREAMTYPE, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SET_FORMAT", VIDEO_SET_FORMAT, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SET_SYSTEM", VIDEO_SET_SYSTEM, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SET_HIGHLIGHT", VIDEO_SET_HIGHLIGHT, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SET_SPU", VIDEO_SET_SPU, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SET_SPU_PALETTE", VIDEO_SET_SPU_PALETTE, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_GET_NAVI", VIDEO_GET_NAVI, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_SET_ATTRIBUTES", VIDEO_SET_ATTRIBUTES, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_GET_SIZE", VIDEO_GET_SIZE, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_GET_FRAME_RATE", VIDEO_GET_FRAME_RATE, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_GET_PTS", VIDEO_GET_PTS, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_GET_FRAME_COUNT", VIDEO_GET_FRAME_COUNT, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_COMMAND", VIDEO_COMMAND, -1, -1 }, // linux/dvb/video.h
    { "VIDEO_TRY_COMMAND", VIDEO_TRY_COMMAND, -1, -1 }, // linux/dvb/video.h
    { "FE_SET_PROPERTY", FE_SET_PROPERTY, -1, -1 }, // linux/dvb/frontend.h
    { "FE_GET_PROPERTY", FE_GET_PROPERTY, -1, -1 }, // linux/dvb/frontend.h
    { "FE_GET_INFO", FE_GET_INFO, -1, -1 }, // linux/dvb/frontend.h
    { "FE_DISEQC_RESET_OVERLOAD", FE_DISEQC_RESET_OVERLOAD, -1, -1 }, // linux/dvb/frontend.h
    { "FE_DISEQC_SEND_MASTER_CMD", FE_DISEQC_SEND_MASTER_CMD, -1, -1 }, // linux/dvb/frontend.h
    { "FE_DISEQC_RECV_SLAVE_REPLY", FE_DISEQC_RECV_SLAVE_REPLY, -1, -1 }, // linux/dvb/frontend.h
    { "FE_DISEQC_SEND_BURST", FE_DISEQC_SEND_BURST, -1, -1 }, // linux/dvb/frontend.h
    { "FE_SET_TONE", FE_SET_TONE, -1, -1 }, // linux/dvb/frontend.h
    { "FE_SET_VOLTAGE", FE_SET_VOLTAGE, -1, -1 }, // linux/dvb/frontend.h
    { "FE_ENABLE_HIGH_LNB_VOLTAGE", FE_ENABLE_HIGH_LNB_VOLTAGE, -1, -1 }, // linux/dvb/frontend.h
    { "FE_READ_STATUS", FE_READ_STATUS, -1, -1 }, // linux/dvb/frontend.h
    { "FE_READ_BER", FE_READ_BER, -1, -1 }, // linux/dvb/frontend.h
    { "FE_READ_SIGNAL_STRENGTH", FE_READ_SIGNAL_STRENGTH, -1, -1 }, // linux/dvb/frontend.h
    { "FE_READ_SNR", FE_READ_SNR, -1, -1 }, // linux/dvb/frontend.h
    { "FE_READ_UNCORRECTED_BLOCKS", FE_READ_UNCORRECTED_BLOCKS, -1, -1 }, // linux/dvb/frontend.h
    { "FE_SET_FRONTEND", FE_SET_FRONTEND, -1, -1 }, // linux/dvb/frontend.h
    { "FE_GET_FRONTEND", FE_GET_FRONTEND, -1, -1 }, // linux/dvb/frontend.h
    { "FE_SET_FRONTEND_TUNE_MODE", FE_SET_FRONTEND_TUNE_MODE, -1, -1 }, // linux/dvb/frontend.h
    { "FE_GET_EVENT", FE_GET_EVENT, -1, -1 }, // linux/dvb/frontend.h
    { "FE_DISHNETWORK_SEND_LEGACY_CMD", FE_DISHNETWORK_SEND_LEGACY_CMD, -1, -1 }, // linux/dvb/frontend.h
    { "AUDIO_STOP", AUDIO_STOP, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_PLAY", AUDIO_PLAY, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_PAUSE", AUDIO_PAUSE, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_CONTINUE", AUDIO_CONTINUE, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_SELECT_SOURCE", AUDIO_SELECT_SOURCE, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_SET_MUTE", AUDIO_SET_MUTE, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_SET_AV_SYNC", AUDIO_SET_AV_SYNC, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_SET_BYPASS_MODE", AUDIO_SET_BYPASS_MODE, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_CHANNEL_SELECT", AUDIO_CHANNEL_SELECT, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_GET_STATUS", AUDIO_GET_STATUS, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_GET_CAPABILITIES", AUDIO_GET_CAPABILITIES, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_CLEAR_BUFFER", AUDIO_CLEAR_BUFFER, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_SET_ID", AUDIO_SET_ID, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_SET_MIXER", AUDIO_SET_MIXER, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_SET_STREAMTYPE", AUDIO_SET_STREAMTYPE, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_SET_EXT_ID", AUDIO_SET_EXT_ID, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_SET_ATTRIBUTES", AUDIO_SET_ATTRIBUTES, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_SET_KARAOKE", AUDIO_SET_KARAOKE, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_GET_PTS", AUDIO_GET_PTS, -1, -1 }, // linux/dvb/audio.h
    { "AUDIO_BILINGUAL_CHANNEL_SELECT", AUDIO_BILINGUAL_CHANNEL_SELECT, -1, -1 }, // linux/dvb/audio.h
    { "DMX_START", DMX_START, -1, -1 }, // linux/dvb/dmx.h
    { "DMX_STOP", DMX_STOP, -1, -1 }, // linux/dvb/dmx.h
    { "DMX_SET_FILTER", DMX_SET_FILTER, -1, -1 }, // linux/dvb/dmx.h
    { "DMX_SET_PES_FILTER", DMX_SET_PES_FILTER, -1, -1 }, // linux/dvb/dmx.h
    { "DMX_SET_BUFFER_SIZE", DMX_SET_BUFFER_SIZE, -1, -1 }, // linux/dvb/dmx.h
    { "DMX_GET_PES_PIDS", DMX_GET_PES_PIDS, -1, -1 }, // linux/dvb/dmx.h
    { "DMX_GET_CAPS", DMX_GET_CAPS, -1, -1 }, // linux/dvb/dmx.h
    { "DMX_SET_SOURCE", DMX_SET_SOURCE, -1, -1 }, // linux/dvb/dmx.h
    { "DMX_GET_STC", DMX_GET_STC, -1, -1 }, // linux/dvb/dmx.h
    { "DMX_ADD_PID", DMX_ADD_PID, -1, -1 }, // linux/dvb/dmx.h
    { "DMX_REMOVE_PID", DMX_REMOVE_PID, -1, -1 }, // linux/dvb/dmx.h
    { "NET_ADD_IF", NET_ADD_IF, -1, -1 }, // linux/dvb/net.h
    { "NET_REMOVE_IF", NET_REMOVE_IF, -1, -1 }, // linux/dvb/net.h
    { "NET_GET_IF", NET_GET_IF, -1, -1 }, // linux/dvb/net.h
    { "__NET_ADD_IF_OLD", __NET_ADD_IF_OLD, -1, -1 }, // linux/dvb/net.h
    { "__NET_GET_IF_OLD", __NET_GET_IF_OLD, -1, -1 }, // linux/dvb/net.h
    { "OSD_SEND_CMD", OSD_SEND_CMD, -1, -1 }, // linux/dvb/osd.h
    { "OSD_GET_CAPABILITY", OSD_GET_CAPABILITY, -1, -1 }, // linux/dvb/osd.h
    { "ATMLEC_CTRL", ATMLEC_CTRL, -1, -1 }, // linux/atmlec.h
    { "ATMLEC_DATA", ATMLEC_DATA, -1, -1 }, // linux/atmlec.h
    { "ATMLEC_MCAST", ATMLEC_MCAST, -1, -1 }, // linux/atmlec.h
    { "MATROXFB_SET_OUTPUT_MODE", MATROXFB_SET_OUTPUT_MODE, -1, -1 }, // linux/matroxfb.h
    { "MATROXFB_GET_OUTPUT_MODE", MATROXFB_GET_OUTPUT_MODE, -1, -1 }, // linux/matroxfb.h
    { "MATROXFB_SET_OUTPUT_CONNECTION", MATROXFB_SET_OUTPUT_CONNECTION, -1, -1 }, // linux/matroxfb.h
    { "MATROXFB_GET_OUTPUT_CONNECTION", MATROXFB_GET_OUTPUT_CONNECTION, -1, -1 }, // linux/matroxfb.h
    { "MATROXFB_GET_AVAILABLE_OUTPUTS", MATROXFB_GET_AVAILABLE_OUTPUTS, -1, -1 }, // linux/matroxfb.h
    { "MATROXFB_GET_ALL_OUTPUTS", MATROXFB_GET_ALL_OUTPUTS, -1, -1 }, // linux/matroxfb.h
    { "VHOST_GET_FEATURES", VHOST_GET_FEATURES, -1, -1 }, // linux/vhost.h
    { "VHOST_SET_FEATURES", VHOST_SET_FEATURES, -1, -1 }, // linux/vhost.h
    { "VHOST_SET_OWNER", VHOST_SET_OWNER, -1, -1 }, // linux/vhost.h
    { "VHOST_RESET_OWNER", VHOST_RESET_OWNER, -1, -1 }, // linux/vhost.h
    { "VHOST_SET_MEM_TABLE", VHOST_SET_MEM_TABLE, -1, -1 }, // linux/vhost.h
    { "VHOST_SET_LOG_BASE", VHOST_SET_LOG_BASE, -1, -1 }, // linux/vhost.h
    { "VHOST_SET_LOG_FD", VHOST_SET_LOG_FD, -1, -1 }, // linux/vhost.h
    { "VHOST_SET_VRING_NUM", VHOST_SET_VRING_NUM, -1, -1 }, // linux/vhost.h
    { "VHOST_SET_VRING_ADDR", VHOST_SET_VRING_ADDR, -1, -1 }, // linux/vhost.h
    { "VHOST_SET_VRING_BASE", VHOST_SET_VRING_BASE, -1, -1 }, // linux/vhost.h
    { "VHOST_GET_VRING_BASE", VHOST_GET_VRING_BASE, -1, -1 }, // linux/vhost.h
    { "VHOST_SET_VRING_KICK", VHOST_SET_VRING_KICK, -1, -1 }, // linux/vhost.h
    { "VHOST_SET_VRING_CALL", VHOST_SET_VRING_CALL, -1, -1 }, // linux/vhost.h
    { "VHOST_SET_VRING_ERR", VHOST_SET_VRING_ERR, -1, -1 }, // linux/vhost.h
    { "VHOST_NET_SET_BACKEND", VHOST_NET_SET_BACKEND, -1, -1 }, // linux/vhost.h
    { "VHOST_SCSI_SET_ENDPOINT", VHOST_SCSI_SET_ENDPOINT, -1, -1 }, // linux/vhost.h
    { "VHOST_SCSI_CLEAR_ENDPOINT", VHOST_SCSI_CLEAR_ENDPOINT, -1, -1 }, // linux/vhost.h
    { "VHOST_SCSI_GET_ABI_VERSION", VHOST_SCSI_GET_ABI_VERSION, -1, -1 }, // linux/vhost.h
    { "VHOST_SCSI_SET_EVENTS_MISSED", VHOST_SCSI_SET_EVENTS_MISSED, -1, -1 }, // linux/vhost.h
    { "VHOST_SCSI_GET_EVENTS_MISSED", VHOST_SCSI_GET_EVENTS_MISSED, -1, -1 }, // linux/vhost.h
    { "PPS_GETPARAMS", PPS_GETPARAMS, -1, -1 }, // linux/pps.h
    { "PPS_SETPARAMS", PPS_SETPARAMS, -1, -1 }, // linux/pps.h
    { "PPS_GETCAP", PPS_GETCAP, -1, -1 }, // linux/pps.h
    { "PPS_FETCH", PPS_FETCH, -1, -1 }, // linux/pps.h
    { "PPS_KC_BIND", PPS_KC_BIND, -1, -1 }, // linux/pps.h
    { "VFIO_GET_API_VERSION", VFIO_GET_API_VERSION, -1, -1 }, // linux/vfio.h
    { "VFIO_CHECK_EXTENSION", VFIO_CHECK_EXTENSION, -1, -1 }, // linux/vfio.h
    { "VFIO_SET_IOMMU", VFIO_SET_IOMMU, -1, -1 }, // linux/vfio.h
    { "VFIO_GROUP_GET_STATUS", VFIO_GROUP_GET_STATUS, -1, -1 }, // linux/vfio.h
    { "VFIO_GROUP_SET_CONTAINER", VFIO_GROUP_SET_CONTAINER, -1, -1 }, // linux/vfio.h
    { "VFIO_GROUP_UNSET_CONTAINER", VFIO_GROUP_UNSET_CONTAINER, -1, -1 }, // linux/vfio.h
    { "VFIO_GROUP_GET_DEVICE_FD", VFIO_GROUP_GET_DEVICE_FD, -1, -1 }, // linux/vfio.h
    { "VFIO_DEVICE_GET_INFO", VFIO_DEVICE_GET_INFO, -1, -1 }, // linux/vfio.h
    { "VFIO_DEVICE_GET_REGION_INFO", VFIO_DEVICE_GET_REGION_INFO, -1, -1 }, // linux/vfio.h
    { "VFIO_DEVICE_GET_IRQ_INFO", VFIO_DEVICE_GET_IRQ_INFO, -1, -1 }, // linux/vfio.h
    { "VFIO_DEVICE_SET_IRQS", VFIO_DEVICE_SET_IRQS, -1, -1 }, // linux/vfio.h
    { "VFIO_DEVICE_RESET", VFIO_DEVICE_RESET, -1, -1 }, // linux/vfio.h
    { "VFIO_DEVICE_GET_PCI_HOT_RESET_INFO", VFIO_DEVICE_GET_PCI_HOT_RESET_INFO, -1, -1 }, // linux/vfio.h
    { "VFIO_DEVICE_PCI_HOT_RESET", VFIO_DEVICE_PCI_HOT_RESET, -1, -1 }, // linux/vfio.h
    { "VFIO_IOMMU_GET_INFO", VFIO_IOMMU_GET_INFO, -1, -1 }, // linux/vfio.h
    { "VFIO_IOMMU_MAP_DMA", VFIO_IOMMU_MAP_DMA, -1, -1 }, // linux/vfio.h
    { "VFIO_IOMMU_UNMAP_DMA", VFIO_IOMMU_UNMAP_DMA, -1, -1 }, // linux/vfio.h
    { "VFIO_IOMMU_ENABLE", VFIO_IOMMU_ENABLE, -1, -1 }, // linux/vfio.h
    { "VFIO_IOMMU_DISABLE", VFIO_IOMMU_DISABLE, -1, -1 }, // linux/vfio.h
    { "VFIO_IOMMU_SPAPR_TCE_GET_INFO", VFIO_IOMMU_SPAPR_TCE_GET_INFO, -1, -1 }, // linux/vfio.h
    { "CM_IOCGATR", CM_IOCGATR, -1, -1 }, // linux/cm4000_cs.h
    { "CM_IOSDBGLVL", CM_IOSDBGLVL, -1, -1 }, // linux/cm4000_cs.h
    { "TUNSETNOCSUM", TUNSETNOCSUM, -1, -1 }, // linux/if_tun.h
    { "TUNSETDEBUG", TUNSETDEBUG, -1, -1 }, // linux/if_tun.h
    { "TUNSETIFF", TUNSETIFF, -1, -1 }, // linux/if_tun.h
    { "TUNSETPERSIST", TUNSETPERSIST, -1, -1 }, // linux/if_tun.h
    { "TUNSETOWNER", TUNSETOWNER, -1, -1 }, // linux/if_tun.h
    { "TUNSETLINK", TUNSETLINK, -1, -1 }, // linux/if_tun.h
    { "TUNSETGROUP", TUNSETGROUP, -1, -1 }, // linux/if_tun.h
    { "TUNGETFEATURES", TUNGETFEATURES, -1, -1 }, // linux/if_tun.h
    { "TUNSETOFFLOAD", TUNSETOFFLOAD, -1, -1 }, // linux/if_tun.h
    { "TUNSETTXFILTER", TUNSETTXFILTER, -1, -1 }, // linux/if_tun.h
    { "TUNGETIFF", TUNGETIFF, -1, -1 }, // linux/if_tun.h
    { "TUNGETSNDBUF", TUNGETSNDBUF, -1, -1 }, // linux/if_tun.h
    { "TUNSETSNDBUF", TUNSETSNDBUF, -1, -1 }, // linux/if_tun.h
    { "TUNATTACHFILTER", TUNATTACHFILTER, -1, -1 }, // linux/if_tun.h
    { "TUNDETACHFILTER", TUNDETACHFILTER, -1, -1 }, // linux/if_tun.h
    { "TUNGETVNETHDRSZ", TUNGETVNETHDRSZ, -1, -1 }, // linux/if_tun.h
    { "TUNSETVNETHDRSZ", TUNSETVNETHDRSZ, -1, -1 }, // linux/if_tun.h
    { "TUNSETQUEUE", TUNSETQUEUE, -1, -1 }, // linux/if_tun.h
    { "TUNSETIFINDEX", TUNSETIFINDEX, -1, -1 }, // linux/if_tun.h
    { "TUNGETFILTER", TUNGETFILTER, -1, -1 }, // linux/if_tun.h
    { "FBIO_WAITEVENT", FBIO_WAITEVENT, -1, -1 }, // linux/arcfb.h
    { "FBIO_GETCONTROL2", FBIO_GETCONTROL2, -1, -1 }, // linux/arcfb.h
    { "HIDIOCGVERSION", HIDIOCGVERSION, -1, -1 }, // linux/hiddev.h
    { "HIDIOCAPPLICATION", HIDIOCAPPLICATION, -1, -1 }, // linux/hiddev.h
    { "HIDIOCGDEVINFO", HIDIOCGDEVINFO, -1, -1 }, // linux/hiddev.h
    { "HIDIOCGSTRING", HIDIOCGSTRING, -1, -1 }, // linux/hiddev.h
    { "HIDIOCINITREPORT", HIDIOCINITREPORT, -1, -1 }, // linux/hiddev.h
    { "HIDIOCGREPORT", HIDIOCGREPORT, -1, -1 }, // linux/hiddev.h
    { "HIDIOCSREPORT", HIDIOCSREPORT, -1, -1 }, // linux/hiddev.h
    { "HIDIOCGREPORTINFO", HIDIOCGREPORTINFO, -1, -1 }, // linux/hiddev.h
    { "HIDIOCGFIELDINFO", HIDIOCGFIELDINFO, -1, -1 }, // linux/hiddev.h
    { "HIDIOCGUSAGE", HIDIOCGUSAGE, -1, -1 }, // linux/hiddev.h
    { "HIDIOCSUSAGE", HIDIOCSUSAGE, -1, -1 }, // linux/hiddev.h
    { "HIDIOCGUCODE", HIDIOCGUCODE, -1, -1 }, // linux/hiddev.h
    { "HIDIOCGFLAG", HIDIOCGFLAG, -1, -1 }, // linux/hiddev.h
    { "HIDIOCSFLAG", HIDIOCSFLAG, -1, -1 }, // linux/hiddev.h
    { "HIDIOCGCOLLECTIONINDEX", HIDIOCGCOLLECTIONINDEX, -1, -1 }, // linux/hiddev.h
    { "HIDIOCGCOLLECTIONINFO", HIDIOCGCOLLECTIONINFO, -1, -1 }, // linux/hiddev.h
    { "HIDIOCGUSAGES", HIDIOCGUSAGES, -1, -1 }, // linux/hiddev.h
    { "HIDIOCSUSAGES", HIDIOCSUSAGES, -1, -1 }, // linux/hiddev.h
    { "PTP_CLOCK_GETCAPS", PTP_CLOCK_GETCAPS, -1, -1 }, // linux/ptp_clock.h
    { "PTP_EXTTS_REQUEST", PTP_EXTTS_REQUEST, -1, -1 }, // linux/ptp_clock.h
    { "PTP_PEROUT_REQUEST", PTP_PEROUT_REQUEST, -1, -1 }, // linux/ptp_clock.h
    { "PTP_ENABLE_PPS", PTP_ENABLE_PPS, -1, -1 }, // linux/ptp_clock.h
    { "PTP_SYS_OFFSET", PTP_SYS_OFFSET, -1, -1 }, // linux/ptp_clock.h
    { "IPMICTL_SEND_COMMAND", IPMICTL_SEND_COMMAND, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_SEND_COMMAND_SETTIME", IPMICTL_SEND_COMMAND_SETTIME, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_RECEIVE_MSG", IPMICTL_RECEIVE_MSG, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_RECEIVE_MSG_TRUNC", IPMICTL_RECEIVE_MSG_TRUNC, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_REGISTER_FOR_CMD", IPMICTL_REGISTER_FOR_CMD, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_UNREGISTER_FOR_CMD", IPMICTL_UNREGISTER_FOR_CMD, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_REGISTER_FOR_CMD_CHANS", IPMICTL_REGISTER_FOR_CMD_CHANS, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_UNREGISTER_FOR_CMD_CHANS", IPMICTL_UNREGISTER_FOR_CMD_CHANS, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_SET_GETS_EVENTS_CMD", IPMICTL_SET_GETS_EVENTS_CMD, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_SET_MY_ADDRESS_CMD", IPMICTL_SET_MY_ADDRESS_CMD, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_GET_MY_ADDRESS_CMD", IPMICTL_GET_MY_ADDRESS_CMD, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_SET_MY_LUN_CMD", IPMICTL_SET_MY_LUN_CMD, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_GET_MY_LUN_CMD", IPMICTL_GET_MY_LUN_CMD, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_SET_TIMING_PARMS_CMD", IPMICTL_SET_TIMING_PARMS_CMD, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_GET_TIMING_PARMS_CMD", IPMICTL_GET_TIMING_PARMS_CMD, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_GET_MAINTENANCE_MODE_CMD", IPMICTL_GET_MAINTENANCE_MODE_CMD, -1, -1 }, // linux/ipmi.h
    { "IPMICTL_SET_MAINTENANCE_MODE_CMD", IPMICTL_SET_MAINTENANCE_MODE_CMD, -1, -1 }, // linux/ipmi.h
    { "HE_GET_REG", HE_GET_REG, -1, -1 }, // linux/atm_he.h
    { "NVRAM_INIT", NVRAM_INIT, -1, -1 }, // linux/nvram.h
    { "NVRAM_SETCKS", NVRAM_SETCKS, -1, -1 }, // linux/nvram.h
    { "DM_VERSION", DM_VERSION, -1, -1 }, // linux/dm-ioctl.h
    { "DM_REMOVE_ALL", DM_REMOVE_ALL, -1, -1 }, // linux/dm-ioctl.h
    { "DM_LIST_DEVICES", DM_LIST_DEVICES, -1, -1 }, // linux/dm-ioctl.h
    { "DM_DEV_CREATE", DM_DEV_CREATE, -1, -1 }, // linux/dm-ioctl.h
    { "DM_DEV_REMOVE", DM_DEV_REMOVE, -1, -1 }, // linux/dm-ioctl.h
    { "DM_DEV_RENAME", DM_DEV_RENAME, -1, -1 }, // linux/dm-ioctl.h
    { "DM_DEV_SUSPEND", DM_DEV_SUSPEND, -1, -1 }, // linux/dm-ioctl.h
    { "DM_DEV_STATUS", DM_DEV_STATUS, -1, -1 }, // linux/dm-ioctl.h
    { "DM_DEV_WAIT", DM_DEV_WAIT, -1, -1 }, // linux/dm-ioctl.h
    { "DM_TABLE_LOAD", DM_TABLE_LOAD, -1, -1 }, // linux/dm-ioctl.h
    { "DM_TABLE_CLEAR", DM_TABLE_CLEAR, -1, -1 }, // linux/dm-ioctl.h
    { "DM_TABLE_DEPS", DM_TABLE_DEPS, -1, -1 }, // linux/dm-ioctl.h
    { "DM_TABLE_STATUS", DM_TABLE_STATUS, -1, -1 }, // linux/dm-ioctl.h
    { "DM_LIST_VERSIONS", DM_LIST_VERSIONS, -1, -1 }, // linux/dm-ioctl.h
    { "DM_TARGET_MSG", DM_TARGET_MSG, -1, -1 }, // linux/dm-ioctl.h
    { "DM_DEV_SET_GEOMETRY", DM_DEV_SET_GEOMETRY, -1, -1 }, // linux/dm-ioctl.h
    { "CCISS_GETPCIINFO", CCISS_GETPCIINFO, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_GETINTINFO", CCISS_GETINTINFO, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_SETINTINFO", CCISS_SETINTINFO, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_GETNODENAME", CCISS_GETNODENAME, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_SETNODENAME", CCISS_SETNODENAME, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_GETHEARTBEAT", CCISS_GETHEARTBEAT, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_GETBUSTYPES", CCISS_GETBUSTYPES, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_GETFIRMVER", CCISS_GETFIRMVER, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_GETDRIVVER", CCISS_GETDRIVVER, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_REVALIDVOLS", CCISS_REVALIDVOLS, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_PASSTHRU", CCISS_PASSTHRU, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_DEREGDISK", CCISS_DEREGDISK, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_REGNEWDISK", CCISS_REGNEWDISK, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_REGNEWD", CCISS_REGNEWD, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_RESCANDISK", CCISS_RESCANDISK, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_GETLUNINFO", CCISS_GETLUNINFO, -1, -1 }, // linux/cciss_ioctl.h
    { "CCISS_BIG_PASSTHRU", CCISS_BIG_PASSTHRU, -1, -1 }, // linux/cciss_ioctl.h
    { "VFAT_IOCTL_READDIR_BOTH", VFAT_IOCTL_READDIR_BOTH, -1, -1 }, // linux/msdos_fs.h
    { "VFAT_IOCTL_READDIR_SHORT", VFAT_IOCTL_READDIR_SHORT, -1, -1 }, // linux/msdos_fs.h
    { "FAT_IOCTL_GET_ATTRIBUTES", FAT_IOCTL_GET_ATTRIBUTES, -1, -1 }, // linux/msdos_fs.h
    { "FAT_IOCTL_SET_ATTRIBUTES", FAT_IOCTL_SET_ATTRIBUTES, -1, -1 }, // linux/msdos_fs.h
    { "FAT_IOCTL_GET_VOLUME_ID", FAT_IOCTL_GET_VOLUME_ID, -1, -1 }, // linux/msdos_fs.h
    { "CAPI_REGISTER", CAPI_REGISTER, -1, -1 }, // linux/capi.h
    { "CAPI_GET_MANUFACTURER", CAPI_GET_MANUFACTURER, -1, -1 }, // linux/capi.h
    { "CAPI_GET_VERSION", CAPI_GET_VERSION, -1, -1 }, // linux/capi.h
    { "CAPI_GET_SERIAL", CAPI_GET_SERIAL, -1, -1 }, // linux/capi.h
    { "CAPI_GET_PROFILE", CAPI_GET_PROFILE, -1, -1 }, // linux/capi.h
    { "CAPI_MANUFACTURER_CMD", CAPI_MANUFACTURER_CMD, -1, -1 }, // linux/capi.h
    { "CAPI_GET_ERRCODE", CAPI_GET_ERRCODE, -1, -1 }, // linux/capi.h
    { "CAPI_INSTALLED", CAPI_INSTALLED, -1, -1 }, // linux/capi.h
    { "CAPI_GET_FLAGS", CAPI_GET_FLAGS, -1, -1 }, // linux/capi.h
    { "CAPI_SET_FLAGS", CAPI_SET_FLAGS, -1, -1 }, // linux/capi.h
    { "CAPI_CLR_FLAGS", CAPI_CLR_FLAGS, -1, -1 }, // linux/capi.h
    { "CAPI_NCCI_OPENCOUNT", CAPI_NCCI_OPENCOUNT, -1, -1 }, // linux/capi.h
    { "CAPI_NCCI_GETUNIT", CAPI_NCCI_GETUNIT, -1, -1 }, // linux/capi.h
    { "USBDEVFS_CONTROL", USBDEVFS_CONTROL, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_BULK", USBDEVFS_BULK, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_RESETEP", USBDEVFS_RESETEP, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_SETINTERFACE", USBDEVFS_SETINTERFACE, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_SETCONFIGURATION", USBDEVFS_SETCONFIGURATION, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_GETDRIVER", USBDEVFS_GETDRIVER, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_SUBMITURB", USBDEVFS_SUBMITURB, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_DISCARDURB", USBDEVFS_DISCARDURB, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_REAPURB", USBDEVFS_REAPURB, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_REAPURB32", USBDEVFS_REAPURB32, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_REAPURBNDELAY", USBDEVFS_REAPURBNDELAY, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_REAPURBNDELAY32", USBDEVFS_REAPURBNDELAY32, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_DISCSIGNAL", USBDEVFS_DISCSIGNAL, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_CLAIMINTERFACE", USBDEVFS_CLAIMINTERFACE, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_RELEASEINTERFACE", USBDEVFS_RELEASEINTERFACE, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_CONNECTINFO", USBDEVFS_CONNECTINFO, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_IOCTL", USBDEVFS_IOCTL, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_HUB_PORTINFO", USBDEVFS_HUB_PORTINFO, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_RESET", USBDEVFS_RESET, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_CLEAR_HALT", USBDEVFS_CLEAR_HALT, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_DISCONNECT", USBDEVFS_DISCONNECT, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_CONNECT", USBDEVFS_CONNECT, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_CLAIM_PORT", USBDEVFS_CLAIM_PORT, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_RELEASE_PORT", USBDEVFS_RELEASE_PORT, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_GET_CAPABILITIES", USBDEVFS_GET_CAPABILITIES, -1, -1 }, // linux/usbdevice_fs.h
    { "USBDEVFS_DISCONNECT_CLAIM", USBDEVFS_DISCONNECT_CLAIM, -1, -1 }, // linux/usbdevice_fs.h
    { "RFKILL_IOCTL_NOINPUT", RFKILL_IOCTL_NOINPUT, -1, -1 }, // linux/rfkill.h
    { "CHIOMOVE", CHIOMOVE, -1, -1 }, // linux/chio.h
    { "CHIOEXCHANGE", CHIOEXCHANGE, -1, -1 }, // linux/chio.h
    { "CHIOPOSITION", CHIOPOSITION, -1, -1 }, // linux/chio.h
    { "CHIOGPICKER", CHIOGPICKER, -1, -1 }, // linux/chio.h
    { "CHIOSPICKER", CHIOSPICKER, -1, -1 }, // linux/chio.h
    { "CHIOGPARAMS", CHIOGPARAMS, -1, -1 }, // linux/chio.h
    { "CHIOGSTATUS", CHIOGSTATUS, -1, -1 }, // linux/chio.h
    { "CHIOGELEM", CHIOGELEM, -1, -1 }, // linux/chio.h
    { "CHIOINITELEM", CHIOINITELEM, -1, -1 }, // linux/chio.h
    { "CHIOSVOLTAG", CHIOSVOLTAG, -1, -1 }, // linux/chio.h
    { "CHIOGVPARAMS", CHIOGVPARAMS, -1, -1 }, // linux/chio.h
    { "PPPIOCGCALLINFO", PPPIOCGCALLINFO, -1, -1 }, // linux/isdn_ppp.h
    { "PPPIOCBUNDLE", PPPIOCBUNDLE, -1, -1 }, // linux/isdn_ppp.h
    { "PPPIOCGMPFLAGS", PPPIOCGMPFLAGS, -1, -1 }, // linux/isdn_ppp.h
    { "PPPIOCSMPFLAGS", PPPIOCSMPFLAGS, -1, -1 }, // linux/isdn_ppp.h
    { "PPPIOCSMPMTU", PPPIOCSMPMTU, -1, -1 }, // linux/isdn_ppp.h
    { "PPPIOCSMPMRU", PPPIOCSMPMRU, -1, -1 }, // linux/isdn_ppp.h
    { "PPPIOCGCOMPRESSORS", PPPIOCGCOMPRESSORS, -1, -1 }, // linux/isdn_ppp.h
    { "PPPIOCSCOMPRESSOR", PPPIOCSCOMPRESSOR, -1, -1 }, // linux/isdn_ppp.h
    { "PPPIOCGIFNAME", PPPIOCGIFNAME, -1, -1 }, // linux/isdn_ppp.h
    { "HIDIOCGRDESCSIZE", HIDIOCGRDESCSIZE, -1, -1 }, // linux/hidraw.h
    { "HIDIOCGRDESC", HIDIOCGRDESC, -1, -1 }, // linux/hidraw.h
    { "HIDIOCGRAWINFO", HIDIOCGRAWINFO, -1, -1 }, // linux/hidraw.h
    { "EVIOCGVERSION", EVIOCGVERSION, -1, -1 }, // linux/input.h
    { "EVIOCGID", EVIOCGID, -1, -1 }, // linux/input.h
    { "EVIOCGREP", EVIOCGREP, -1, -1 }, // linux/input.h
    { "EVIOCSREP", EVIOCSREP, -1, -1 }, // linux/input.h
    { "EVIOCGKEYCODE", EVIOCGKEYCODE, -1, -1 }, // linux/input.h
    { "EVIOCGKEYCODE_V2", EVIOCGKEYCODE_V2, -1, -1 }, // linux/input.h
    { "EVIOCSKEYCODE", EVIOCSKEYCODE, -1, -1 }, // linux/input.h
    { "EVIOCSKEYCODE_V2", EVIOCSKEYCODE_V2, -1, -1 }, // linux/input.h
    { "EVIOCRMFF", EVIOCRMFF, -1, -1 }, // linux/input.h
    { "EVIOCGEFFECTS", EVIOCGEFFECTS, -1, -1 }, // linux/input.h
    { "EVIOCGRAB", EVIOCGRAB, -1, -1 }, // linux/input.h
    { "EVIOCREVOKE", EVIOCREVOKE, -1, -1 }, // linux/input.h
    { "EVIOCSCLOCKID", EVIOCSCLOCKID, -1, -1 }, // linux/input.h
    { "SPI_IOC_RD_MODE", SPI_IOC_RD_MODE, -1, -1 }, // linux/spi/spidev.h
    { "SPI_IOC_WR_MODE", SPI_IOC_WR_MODE, -1, -1 }, // linux/spi/spidev.h
    { "SPI_IOC_RD_LSB_FIRST", SPI_IOC_RD_LSB_FIRST, -1, -1 }, // linux/spi/spidev.h
    { "SPI_IOC_WR_LSB_FIRST", SPI_IOC_WR_LSB_FIRST, -1, -1 }, // linux/spi/spidev.h
    { "SPI_IOC_RD_BITS_PER_WORD", SPI_IOC_RD_BITS_PER_WORD, -1, -1 }, // linux/spi/spidev.h
    { "SPI_IOC_WR_BITS_PER_WORD", SPI_IOC_WR_BITS_PER_WORD, -1, -1 }, // linux/spi/spidev.h
    { "SPI_IOC_RD_MAX_SPEED_HZ", SPI_IOC_RD_MAX_SPEED_HZ, -1, -1 }, // linux/spi/spidev.h
    { "SPI_IOC_WR_MAX_SPEED_HZ", SPI_IOC_WR_MAX_SPEED_HZ, -1, -1 }, // linux/spi/spidev.h
    { "MEYEIOC_SYNC", MEYEIOC_SYNC, -1, -1 }, // linux/meye.h
    { "REISERFS_IOC_UNPACK", REISERFS_IOC_UNPACK, -1, -1 }, // linux/reiserfs_fs.h
    { "I8K_GET_SPEED", I8K_GET_SPEED, -1, -1 }, // linux/i8k.h
    { "I8K_GET_FAN", I8K_GET_FAN, -1, -1 }, // linux/i8k.h
    { "I8K_SET_FAN", I8K_SET_FAN, -1, -1 }, // linux/i8k.h
    { "PACKET_CTRL_CMD", PACKET_CTRL_CMD, -1, -1 }, // linux/pktcdvd.h
    { "NS_GETPSTAT", NS_GETPSTAT, -1, -1 }, // linux/atm_nicstar.h
    { "NS_SETBUFLEV", NS_SETBUFLEV, -1, -1 }, // linux/atm_nicstar.h
    { "NS_ADJBUFLEV", NS_ADJBUFLEV, -1, -1 }, // linux/atm_nicstar.h
    { "__KVM_DEPRECATED_MAIN_0x07", __KVM_DEPRECATED_MAIN_0x07, -1, -1 }, // linux/kvm.h
    { "__KVM_DEPRECATED_MAIN_0x08", __KVM_DEPRECATED_MAIN_0x08, -1, -1 }, // linux/kvm.h
    { "__KVM_DEPRECATED_VM_R_0x70", __KVM_DEPRECATED_VM_R_0x70, -1, -1 }, // linux/kvm.h
    { "__KVM_DEPRECATED_VCPU_W_0x87", __KVM_DEPRECATED_VCPU_W_0x87, -1, -1 }, // linux/kvm.h
    { "KVM_GET_API_VERSION", KVM_GET_API_VERSION, -1, -1 }, // linux/kvm.h
    { "KVM_CREATE_VM", KVM_CREATE_VM, -1, -1 }, // linux/kvm.h
    { "KVM_GET_MSR_INDEX_LIST", KVM_GET_MSR_INDEX_LIST, -1, -1 }, // linux/kvm.h
    { "KVM_S390_ENABLE_SIE", KVM_S390_ENABLE_SIE, -1, -1 }, // linux/kvm.h
    { "KVM_CHECK_EXTENSION", KVM_CHECK_EXTENSION, -1, -1 }, // linux/kvm.h
    { "KVM_GET_VCPU_MMAP_SIZE", KVM_GET_VCPU_MMAP_SIZE, -1, -1 }, // linux/kvm.h
    { "KVM_GET_SUPPORTED_CPUID", KVM_GET_SUPPORTED_CPUID, -1, -1 }, // linux/kvm.h
    { "KVM_GET_EMULATED_CPUID", KVM_GET_EMULATED_CPUID, -1, -1 }, // linux/kvm.h
    { "KVM_SET_MEMORY_REGION", KVM_SET_MEMORY_REGION, -1, -1 }, // linux/kvm.h
    { "KVM_CREATE_VCPU", KVM_CREATE_VCPU, -1, -1 }, // linux/kvm.h
    { "KVM_GET_DIRTY_LOG", KVM_GET_DIRTY_LOG, -1, -1 }, // linux/kvm.h
    { "KVM_SET_MEMORY_ALIAS", KVM_SET_MEMORY_ALIAS, -1, -1 }, // linux/kvm.h
    { "KVM_SET_NR_MMU_PAGES", KVM_SET_NR_MMU_PAGES, -1, -1 }, // linux/kvm.h
    { "KVM_GET_NR_MMU_PAGES", KVM_GET_NR_MMU_PAGES, -1, -1 }, // linux/kvm.h
    { "KVM_SET_USER_MEMORY_REGION", KVM_SET_USER_MEMORY_REGION, -1, -1 }, // linux/kvm.h
    { "KVM_SET_TSS_ADDR", KVM_SET_TSS_ADDR, -1, -1 }, // linux/kvm.h
    { "KVM_SET_IDENTITY_MAP_ADDR", KVM_SET_IDENTITY_MAP_ADDR, -1, -1 }, // linux/kvm.h
    { "KVM_S390_UCAS_MAP", KVM_S390_UCAS_MAP, -1, -1 }, // linux/kvm.h
    { "KVM_S390_UCAS_UNMAP", KVM_S390_UCAS_UNMAP, -1, -1 }, // linux/kvm.h
    { "KVM_S390_VCPU_FAULT", KVM_S390_VCPU_FAULT, -1, -1 }, // linux/kvm.h
    { "KVM_CREATE_IRQCHIP", KVM_CREATE_IRQCHIP, -1, -1 }, // linux/kvm.h
    { "KVM_IRQ_LINE", KVM_IRQ_LINE, -1, -1 }, // linux/kvm.h
    { "KVM_GET_IRQCHIP", KVM_GET_IRQCHIP, -1, -1 }, // linux/kvm.h
    { "KVM_SET_IRQCHIP", KVM_SET_IRQCHIP, -1, -1 }, // linux/kvm.h
    { "KVM_CREATE_PIT", KVM_CREATE_PIT, -1, -1 }, // linux/kvm.h
    { "KVM_GET_PIT", KVM_GET_PIT, -1, -1 }, // linux/kvm.h
    { "KVM_SET_PIT", KVM_SET_PIT, -1, -1 }, // linux/kvm.h
    { "KVM_IRQ_LINE_STATUS", KVM_IRQ_LINE_STATUS, -1, -1 }, // linux/kvm.h
    { "KVM_ASSIGN_PCI_DEVICE", KVM_ASSIGN_PCI_DEVICE, -1, -1 }, // linux/kvm.h
    { "KVM_SET_GSI_ROUTING", KVM_SET_GSI_ROUTING, -1, -1 }, // linux/kvm.h
    { "KVM_ASSIGN_DEV_IRQ", KVM_ASSIGN_DEV_IRQ, -1, -1 }, // linux/kvm.h
    { "KVM_REINJECT_CONTROL", KVM_REINJECT_CONTROL, -1, -1 }, // linux/kvm.h
    { "KVM_DEASSIGN_PCI_DEVICE", KVM_DEASSIGN_PCI_DEVICE, -1, -1 }, // linux/kvm.h
    { "KVM_ASSIGN_SET_MSIX_NR", KVM_ASSIGN_SET_MSIX_NR, -1, -1 }, // linux/kvm.h
    { "KVM_ASSIGN_SET_MSIX_ENTRY", KVM_ASSIGN_SET_MSIX_ENTRY, -1, -1 }, // linux/kvm.h
    { "KVM_DEASSIGN_DEV_IRQ", KVM_DEASSIGN_DEV_IRQ, -1, -1 }, // linux/kvm.h
    { "KVM_IRQFD", KVM_IRQFD, -1, -1 }, // linux/kvm.h
    { "KVM_CREATE_PIT2", KVM_CREATE_PIT2, -1, -1 }, // linux/kvm.h
    { "KVM_SET_BOOT_CPU_ID", KVM_SET_BOOT_CPU_ID, -1, -1 }, // linux/kvm.h
    { "KVM_IOEVENTFD", KVM_IOEVENTFD, -1, -1 }, // linux/kvm.h
    { "KVM_XEN_HVM_CONFIG", KVM_XEN_HVM_CONFIG, -1, -1 }, // linux/kvm.h
    { "KVM_SET_CLOCK", KVM_SET_CLOCK, -1, -1 }, // linux/kvm.h
    { "KVM_GET_CLOCK", KVM_GET_CLOCK, -1, -1 }, // linux/kvm.h
    { "KVM_GET_PIT2", KVM_GET_PIT2, -1, -1 }, // linux/kvm.h
    { "KVM_SET_PIT2", KVM_SET_PIT2, -1, -1 }, // linux/kvm.h
    { "KVM_PPC_GET_PVINFO", KVM_PPC_GET_PVINFO, -1, -1 }, // linux/kvm.h
    { "KVM_SET_TSC_KHZ", KVM_SET_TSC_KHZ, -1, -1 }, // linux/kvm.h
    { "KVM_GET_TSC_KHZ", KVM_GET_TSC_KHZ, -1, -1 }, // linux/kvm.h
    { "KVM_ASSIGN_SET_INTX_MASK", KVM_ASSIGN_SET_INTX_MASK, -1, -1 }, // linux/kvm.h
    { "KVM_SIGNAL_MSI", KVM_SIGNAL_MSI, -1, -1 }, // linux/kvm.h
    { "KVM_PPC_GET_SMMU_INFO", KVM_PPC_GET_SMMU_INFO, -1, -1 }, // linux/kvm.h
    { "KVM_PPC_ALLOCATE_HTAB", KVM_PPC_ALLOCATE_HTAB, -1, -1 }, // linux/kvm.h
    { "KVM_ARM_SET_DEVICE_ADDR", KVM_ARM_SET_DEVICE_ADDR, -1, -1 }, // linux/kvm.h
    { "KVM_CREATE_DEVICE", KVM_CREATE_DEVICE, -1, -1 }, // linux/kvm.h
    { "KVM_SET_DEVICE_ATTR", KVM_SET_DEVICE_ATTR, -1, -1 }, // linux/kvm.h
    { "KVM_GET_DEVICE_ATTR", KVM_GET_DEVICE_ATTR, -1, -1 }, // linux/kvm.h
    { "KVM_HAS_DEVICE_ATTR", KVM_HAS_DEVICE_ATTR, -1, -1 }, // linux/kvm.h
    { "KVM_RUN", KVM_RUN, -1, -1 }, // linux/kvm.h
    { "KVM_GET_REGS", KVM_GET_REGS, -1, -1 }, // linux/kvm.h
    { "KVM_SET_REGS", KVM_SET_REGS, -1, -1 }, // linux/kvm.h
    { "KVM_GET_SREGS", KVM_GET_SREGS, -1, -1 }, // linux/kvm.h
    { "KVM_SET_SREGS", KVM_SET_SREGS, -1, -1 }, // linux/kvm.h
    { "KVM_TRANSLATE", KVM_TRANSLATE, -1, -1 }, // linux/kvm.h
    { "KVM_INTERRUPT", KVM_INTERRUPT, -1, -1 }, // linux/kvm.h
    { "KVM_GET_MSRS", KVM_GET_MSRS, -1, -1 }, // linux/kvm.h
    { "KVM_SET_MSRS", KVM_SET_MSRS, -1, -1 }, // linux/kvm.h
    { "KVM_SET_CPUID", KVM_SET_CPUID, -1, -1 }, // linux/kvm.h
    { "KVM_SET_SIGNAL_MASK", KVM_SET_SIGNAL_MASK, -1, -1 }, // linux/kvm.h
    { "KVM_GET_FPU", KVM_GET_FPU, -1, -1 }, // linux/kvm.h
    { "KVM_SET_FPU", KVM_SET_FPU, -1, -1 }, // linux/kvm.h
    { "KVM_GET_LAPIC", KVM_GET_LAPIC, -1, -1 }, // linux/kvm.h
    { "KVM_SET_LAPIC", KVM_SET_LAPIC, -1, -1 }, // linux/kvm.h
    { "KVM_SET_CPUID2", KVM_SET_CPUID2, -1, -1 }, // linux/kvm.h
    { "KVM_GET_CPUID2", KVM_GET_CPUID2, -1, -1 }, // linux/kvm.h
    { "KVM_TPR_ACCESS_REPORTING", KVM_TPR_ACCESS_REPORTING, -1, -1 }, // linux/kvm.h
    { "KVM_SET_VAPIC_ADDR", KVM_SET_VAPIC_ADDR, -1, -1 }, // linux/kvm.h
    { "KVM_S390_INTERRUPT", KVM_S390_INTERRUPT, -1, -1 }, // linux/kvm.h
    { "KVM_S390_STORE_STATUS", KVM_S390_STORE_STATUS, -1, -1 }, // linux/kvm.h
    { "KVM_S390_SET_INITIAL_PSW", KVM_S390_SET_INITIAL_PSW, -1, -1 }, // linux/kvm.h
    { "KVM_S390_INITIAL_RESET", KVM_S390_INITIAL_RESET, -1, -1 }, // linux/kvm.h
    { "KVM_GET_MP_STATE", KVM_GET_MP_STATE, -1, -1 }, // linux/kvm.h
    { "KVM_SET_MP_STATE", KVM_SET_MP_STATE, -1, -1 }, // linux/kvm.h
    { "KVM_NMI", KVM_NMI, -1, -1 }, // linux/kvm.h
    { "KVM_SET_GUEST_DEBUG", KVM_SET_GUEST_DEBUG, -1, -1 }, // linux/kvm.h
    { "KVM_X86_SETUP_MCE", KVM_X86_SETUP_MCE, -1, -1 }, // linux/kvm.h
    { "KVM_X86_GET_MCE_CAP_SUPPORTED", KVM_X86_GET_MCE_CAP_SUPPORTED, -1, -1 }, // linux/kvm.h
    { "KVM_X86_SET_MCE", KVM_X86_SET_MCE, -1, -1 }, // linux/kvm.h
    { "KVM_IA64_VCPU_GET_STACK", KVM_IA64_VCPU_GET_STACK, -1, -1 }, // linux/kvm.h
    { "KVM_IA64_VCPU_SET_STACK", KVM_IA64_VCPU_SET_STACK, -1, -1 }, // linux/kvm.h
    { "KVM_GET_VCPU_EVENTS", KVM_GET_VCPU_EVENTS, -1, -1 }, // linux/kvm.h
    { "KVM_SET_VCPU_EVENTS", KVM_SET_VCPU_EVENTS, -1, -1 }, // linux/kvm.h
    { "KVM_GET_DEBUGREGS", KVM_GET_DEBUGREGS, -1, -1 }, // linux/kvm.h
    { "KVM_SET_DEBUGREGS", KVM_SET_DEBUGREGS, -1, -1 }, // linux/kvm.h
    { "KVM_ENABLE_CAP", KVM_ENABLE_CAP, -1, -1 }, // linux/kvm.h
    { "KVM_GET_XSAVE", KVM_GET_XSAVE, -1, -1 }, // linux/kvm.h
    { "KVM_SET_XSAVE", KVM_SET_XSAVE, -1, -1 }, // linux/kvm.h
    { "KVM_GET_XCRS", KVM_GET_XCRS, -1, -1 }, // linux/kvm.h
    { "KVM_SET_XCRS", KVM_SET_XCRS, -1, -1 }, // linux/kvm.h
    { "KVM_DIRTY_TLB", KVM_DIRTY_TLB, -1, -1 }, // linux/kvm.h
    { "KVM_GET_ONE_REG", KVM_GET_ONE_REG, -1, -1 }, // linux/kvm.h
    { "KVM_SET_ONE_REG", KVM_SET_ONE_REG, -1, -1 }, // linux/kvm.h
    { "KVM_KVMCLOCK_CTRL", KVM_KVMCLOCK_CTRL, -1, -1 }, // linux/kvm.h
    { "KVM_GET_REG_LIST", KVM_GET_REG_LIST, -1, -1 }, // linux/kvm.h
    { "ATMSIGD_CTRL", ATMSIGD_CTRL, -1, -1 }, // linux/atmsvc.h
    { "APM_IOC_STANDBY", APM_IOC_STANDBY, -1, -1 }, // linux/apm_bios.h
    { "APM_IOC_SUSPEND", APM_IOC_SUSPEND, -1, -1 }, // linux/apm_bios.h
    { "MIC_VIRTIO_ADD_DEVICE", MIC_VIRTIO_ADD_DEVICE, -1, -1 }, // linux/mic_ioctl.h
    { "MIC_VIRTIO_COPY_DESC", MIC_VIRTIO_COPY_DESC, -1, -1 }, // linux/mic_ioctl.h
    { "MIC_VIRTIO_CONFIG_CHANGE", MIC_VIRTIO_CONFIG_CHANGE, -1, -1 }, // linux/mic_ioctl.h
    { "AUFS_CTL_RDU", AUFS_CTL_RDU, -1, -1 }, // linux/aufs_type.h
    { "AUFS_CTL_RDU_INO", AUFS_CTL_RDU_INO, -1, -1 }, // linux/aufs_type.h
    { "AUFS_CTL_WBR_FD", AUFS_CTL_WBR_FD, -1, -1 }, // linux/aufs_type.h
    { "AUFS_CTL_IBUSY", AUFS_CTL_IBUSY, -1, -1 }, // linux/aufs_type.h
    { "AUFS_CTL_MVDOWN", AUFS_CTL_MVDOWN, -1, -1 }, // linux/aufs_type.h
    { "VIDIOC_SUBDEV_G_FMT", VIDIOC_SUBDEV_G_FMT, -1, -1 }, // linux/v4l2-subdev.h
    { "VIDIOC_SUBDEV_S_FMT", VIDIOC_SUBDEV_S_FMT, -1, -1 }, // linux/v4l2-subdev.h
    { "VIDIOC_SUBDEV_G_CROP", VIDIOC_SUBDEV_G_CROP, -1, -1 }, // linux/v4l2-subdev.h
    { "VIDIOC_SUBDEV_S_CROP", VIDIOC_SUBDEV_S_CROP, -1, -1 }, // linux/v4l2-subdev.h
    { "VIDIOC_SUBDEV_G_EDID", VIDIOC_SUBDEV_G_EDID, -1, -1 }, // linux/v4l2-subdev.h
    { "VIDIOC_SUBDEV_S_EDID", VIDIOC_SUBDEV_S_EDID, -1, -1 }, // linux/v4l2-subdev.h
    { "TOSH_SMM", TOSH_SMM, -1, -1 }, // linux/toshiba.h
    { "PHN_GET_REG", PHN_GET_REG, -1, -1 }, // linux/phantom.h
    { "PHN_SET_REG", PHN_SET_REG, -1, -1 }, // linux/phantom.h
    { "PHN_GET_REGS", PHN_GET_REGS, -1, -1 }, // linux/phantom.h
    { "PHN_SET_REGS", PHN_SET_REGS, -1, -1 }, // linux/phantom.h
    { "PHN_NOT_OH", PHN_NOT_OH, -1, -1 }, // linux/phantom.h
    { "PHN_GETREG", PHN_GETREG, -1, -1 }, // linux/phantom.h
    { "PHN_SETREG", PHN_SETREG, -1, -1 }, // linux/phantom.h
    { "PHN_GETREGS", PHN_GETREGS, -1, -1 }, // linux/phantom.h
    { "PHN_SETREGS", PHN_SETREGS, -1, -1 }, // linux/phantom.h
    { "GIGASET_REDIR", GIGASET_REDIR, -1, -1 }, // linux/gigaset_dev.h
    { "GIGASET_CONFIG", GIGASET_CONFIG, -1, -1 }, // linux/gigaset_dev.h
    { "GIGASET_BRKCHARS", GIGASET_BRKCHARS, -1, -1 }, // linux/gigaset_dev.h
    { "GIGASET_VERSION", GIGASET_VERSION, -1, -1 }, // linux/gigaset_dev.h
    { "BLKPG", BLKPG, -1, -1 }, // linux/blkpg.h
    { "JSIOCGVERSION", JSIOCGVERSION, -1, -1 }, // linux/joystick.h
    { "JSIOCGAXES", JSIOCGAXES, -1, -1 }, // linux/joystick.h
    { "JSIOCGBUTTONS", JSIOCGBUTTONS, -1, -1 }, // linux/joystick.h
    { "JSIOCSCORR", JSIOCSCORR, -1, -1 }, // linux/joystick.h
    { "JSIOCGCORR", JSIOCGCORR, -1, -1 }, // linux/joystick.h
    { "JSIOCSAXMAP", JSIOCSAXMAP, -1, -1 }, // linux/joystick.h
    { "JSIOCGAXMAP", JSIOCGAXMAP, -1, -1 }, // linux/joystick.h
    { "JSIOCSBTNMAP", JSIOCSBTNMAP, -1, -1 }, // linux/joystick.h
    { "JSIOCGBTNMAP", JSIOCGBTNMAP, -1, -1 }, // linux/joystick.h
    { "WDIOC_GETSUPPORT", WDIOC_GETSUPPORT, -1, -1 }, // linux/watchdog.h
    { "WDIOC_GETSTATUS", WDIOC_GETSTATUS, -1, -1 }, // linux/watchdog.h
    { "WDIOC_GETBOOTSTATUS", WDIOC_GETBOOTSTATUS, -1, -1 }, // linux/watchdog.h
    { "WDIOC_GETTEMP", WDIOC_GETTEMP, -1, -1 }, // linux/watchdog.h
    { "WDIOC_SETOPTIONS", WDIOC_SETOPTIONS, -1, -1 }, // linux/watchdog.h
    { "WDIOC_KEEPALIVE", WDIOC_KEEPALIVE, -1, -1 }, // linux/watchdog.h
    { "WDIOC_SETTIMEOUT", WDIOC_SETTIMEOUT, -1, -1 }, // linux/watchdog.h
    { "WDIOC_GETTIMEOUT", WDIOC_GETTIMEOUT, -1, -1 }, // linux/watchdog.h
    { "WDIOC_SETPRETIMEOUT", WDIOC_SETPRETIMEOUT, -1, -1 }, // linux/watchdog.h
    { "WDIOC_GETPRETIMEOUT", WDIOC_GETPRETIMEOUT, -1, -1 }, // linux/watchdog.h
    { "WDIOC_GETTIMELEFT", WDIOC_GETTIMELEFT, -1, -1 }, // linux/watchdog.h
    { "NBD_SET_SOCK", NBD_SET_SOCK, -1, -1 }, // linux/nbd.h
    { "NBD_SET_BLKSIZE", NBD_SET_BLKSIZE, -1, -1 }, // linux/nbd.h
    { "NBD_SET_SIZE", NBD_SET_SIZE, -1, -1 }, // linux/nbd.h
    { "NBD_DO_IT", NBD_DO_IT, -1, -1 }, // linux/nbd.h
    { "NBD_CLEAR_SOCK", NBD_CLEAR_SOCK, -1, -1 }, // linux/nbd.h
    { "NBD_CLEAR_QUE", NBD_CLEAR_QUE, -1, -1 }, // linux/nbd.h
    { "NBD_PRINT_DEBUG", NBD_PRINT_DEBUG, -1, -1 }, // linux/nbd.h
    { "NBD_SET_SIZE_BLOCKS", NBD_SET_SIZE_BLOCKS, -1, -1 }, // linux/nbd.h
    { "NBD_DISCONNECT", NBD_DISCONNECT, -1, -1 }, // linux/nbd.h
    { "NBD_SET_TIMEOUT", NBD_SET_TIMEOUT, -1, -1 }, // linux/nbd.h
    { "NBD_SET_FLAGS", NBD_SET_FLAGS, -1, -1 }, // linux/nbd.h
    { "RNDGETENTCNT", RNDGETENTCNT, -1, -1 }, // linux/random.h
    { "RNDADDTOENTCNT", RNDADDTOENTCNT, -1, -1 }, // linux/random.h
    { "RNDGETPOOL", RNDGETPOOL, -1, -1 }, // linux/random.h
    { "RNDADDENTROPY", RNDADDENTROPY, -1, -1 }, // linux/random.h
    { "RNDZAPENTCNT", RNDZAPENTCNT, -1, -1 }, // linux/random.h
    { "RNDCLEARPOOL", RNDCLEARPOOL, -1, -1 }, // linux/random.h
    { "IVTVFB_IOC_DMA_FRAME", IVTVFB_IOC_DMA_FRAME, -1, -1 }, // linux/ivtvfb.h
    { "AGPIOC_ALLOCATE", AGPIOC_ALLOCATE, -1, -1 }, // linux/agpgart.h
    { "RTC_AIE_ON", RTC_AIE_ON, -1, -1 }, // linux/rtc.h
    { "RTC_AIE_OFF", RTC_AIE_OFF, -1, -1 }, // linux/rtc.h
    { "RTC_UIE_ON", RTC_UIE_ON, -1, -1 }, // linux/rtc.h
    { "RTC_UIE_OFF", RTC_UIE_OFF, -1, -1 }, // linux/rtc.h
    { "RTC_PIE_ON", RTC_PIE_ON, -1, -1 }, // linux/rtc.h
    { "RTC_PIE_OFF", RTC_PIE_OFF, -1, -1 }, // linux/rtc.h
    { "RTC_WIE_ON", RTC_WIE_ON, -1, -1 }, // linux/rtc.h
    { "RTC_WIE_OFF", RTC_WIE_OFF, -1, -1 }, // linux/rtc.h
    { "RTC_ALM_SET", RTC_ALM_SET, -1, -1 }, // linux/rtc.h
    { "RTC_ALM_READ", RTC_ALM_READ, -1, -1 }, // linux/rtc.h
    { "RTC_RD_TIME", RTC_RD_TIME, -1, -1 }, // linux/rtc.h
    { "RTC_SET_TIME", RTC_SET_TIME, -1, -1 }, // linux/rtc.h
    { "RTC_IRQP_READ", RTC_IRQP_READ, -1, -1 }, // linux/rtc.h
    { "RTC_IRQP_SET", RTC_IRQP_SET, -1, -1 }, // linux/rtc.h
    { "RTC_EPOCH_READ", RTC_EPOCH_READ, -1, -1 }, // linux/rtc.h
    { "RTC_EPOCH_SET", RTC_EPOCH_SET, -1, -1 }, // linux/rtc.h
    { "RTC_WKALM_SET", RTC_WKALM_SET, -1, -1 }, // linux/rtc.h
    { "RTC_WKALM_RD", RTC_WKALM_RD, -1, -1 }, // linux/rtc.h
    { "RTC_PLL_GET", RTC_PLL_GET, -1, -1 }, // linux/rtc.h
    { "RTC_PLL_SET", RTC_PLL_SET, -1, -1 }, // linux/rtc.h
    { "RTC_VL_READ", RTC_VL_READ, -1, -1 }, // linux/rtc.h
    { "RTC_VL_CLR", RTC_VL_CLR, -1, -1 }, // linux/rtc.h
    { "FBIO_CURSOR", FBIO_CURSOR, -1, -1 }, // linux/fb.h
    { "FBIOGET_VBLANK", FBIOGET_VBLANK, -1, -1 }, // linux/fb.h
    { "FBIO_WAITFORVSYNC", FBIO_WAITFORVSYNC, -1, -1 }, // linux/fb.h
    { "ATMMPC_CTRL", ATMMPC_CTRL, -1, -1 }, // linux/atmmpc.h
    { "ATMMPC_DATA", ATMMPC_DATA, -1, -1 }, // linux/atmmpc.h
    { "BLKROSET", BLKROSET, -1, -1 }, // linux/fs.h
    { "BLKROGET", BLKROGET, -1, -1 }, // linux/fs.h
    { "BLKRRPART", BLKRRPART, -1, -1 }, // linux/fs.h
    { "BLKGETSIZE", BLKGETSIZE, -1, -1 }, // linux/fs.h
    { "BLKFLSBUF", BLKFLSBUF, -1, -1 }, // linux/fs.h
    { "BLKRASET", BLKRASET, -1, -1 }, // linux/fs.h
    { "BLKRAGET", BLKRAGET, -1, -1 }, // linux/fs.h
    { "BLKFRASET", BLKFRASET, -1, -1 }, // linux/fs.h
    { "BLKFRAGET", BLKFRAGET, -1, -1 }, // linux/fs.h
    { "BLKSECTSET", BLKSECTSET, -1, -1 }, // linux/fs.h
    { "BLKSECTGET", BLKSECTGET, -1, -1 }, // linux/fs.h
    { "BLKSSZGET", BLKSSZGET, -1, -1 }, // linux/fs.h
    { "BLKPG", BLKPG, -1, -1 }, // linux/fs.h
    { "BLKBSZGET", BLKBSZGET, -1, -1 }, // linux/fs.h
    { "BLKBSZSET", BLKBSZSET, -1, -1 }, // linux/fs.h
    { "BLKGETSIZE64", BLKGETSIZE64, -1, -1 }, // linux/fs.h
    { "BLKTRACESTART", BLKTRACESTART, -1, -1 }, // linux/fs.h
    { "BLKTRACESTOP", BLKTRACESTOP, -1, -1 }, // linux/fs.h
    { "BLKTRACETEARDOWN", BLKTRACETEARDOWN, -1, -1 }, // linux/fs.h
    { "BLKDISCARD", BLKDISCARD, -1, -1 }, // linux/fs.h
    { "BLKIOMIN", BLKIOMIN, -1, -1 }, // linux/fs.h
    { "BLKIOOPT", BLKIOOPT, -1, -1 }, // linux/fs.h
    { "BLKALIGNOFF", BLKALIGNOFF, -1, -1 }, // linux/fs.h
    { "BLKPBSZGET", BLKPBSZGET, -1, -1 }, // linux/fs.h
    { "BLKDISCARDZEROES", BLKDISCARDZEROES, -1, -1 }, // linux/fs.h
    { "BLKSECDISCARD", BLKSECDISCARD, -1, -1 }, // linux/fs.h
    { "BLKROTATIONAL", BLKROTATIONAL, -1, -1 }, // linux/fs.h
    { "BLKZEROOUT", BLKZEROOUT, -1, -1 }, // linux/fs.h
    { "FIBMAP", FIBMAP, -1, -1 }, // linux/fs.h
    { "FIGETBSZ", FIGETBSZ, -1, -1 }, // linux/fs.h
    { "FIFREEZE", FIFREEZE, -1, -1 }, // linux/fs.h
    { "FITHAW", FITHAW, -1, -1 }, // linux/fs.h
    { "FITRIM", FITRIM, -1, -1 }, // linux/fs.h
    { "FS_IOC_GETFLAGS", FS_IOC_GETFLAGS, -1, -1 }, // linux/fs.h
    { "FS_IOC_SETFLAGS", FS_IOC_SETFLAGS, -1, -1 }, // linux/fs.h
    { "FS_IOC_GETVERSION", FS_IOC_GETVERSION, -1, -1 }, // linux/fs.h
    { "FS_IOC_SETVERSION", FS_IOC_SETVERSION, -1, -1 }, // linux/fs.h
    { "FS_IOC32_GETFLAGS", FS_IOC32_GETFLAGS, -1, -1 }, // linux/fs.h
    { "FS_IOC32_SETFLAGS", FS_IOC32_SETFLAGS, -1, -1 }, // linux/fs.h
    { "FS_IOC32_GETVERSION", FS_IOC32_GETVERSION, -1, -1 }, // linux/fs.h
    { "FS_IOC32_SETVERSION", FS_IOC32_SETVERSION, -1, -1 }, // linux/fs.h
    { "ATMARPD_CTRL", ATMARPD_CTRL, -1, -1 }, // linux/atmarp.h
    { "ATMARP_MKIP", ATMARP_MKIP, -1, -1 }, // linux/atmarp.h
    { "ATMARP_SETENTRY", ATMARP_SETENTRY, -1, -1 }, // linux/atmarp.h
    { "ATMARP_ENCAP", ATMARP_ENCAP, -1, -1 }, // linux/atmarp.h
    { "AUTOFS_IOC_EXPIRE_MULTI", AUTOFS_IOC_EXPIRE_MULTI, -1, -1 }, // linux/auto_fs4.h
    { "AUTOFS_IOC_PROTOSUBVER", AUTOFS_IOC_PROTOSUBVER, -1, -1 }, // linux/auto_fs4.h
    { "AUTOFS_IOC_ASKUMOUNT", AUTOFS_IOC_ASKUMOUNT, -1, -1 }, // linux/auto_fs4.h
    { "FW_CDEV_IOC_GET_INFO", FW_CDEV_IOC_GET_INFO, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_SEND_REQUEST", FW_CDEV_IOC_SEND_REQUEST, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_ALLOCATE", FW_CDEV_IOC_ALLOCATE, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_DEALLOCATE", FW_CDEV_IOC_DEALLOCATE, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_SEND_RESPONSE", FW_CDEV_IOC_SEND_RESPONSE, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_INITIATE_BUS_RESET", FW_CDEV_IOC_INITIATE_BUS_RESET, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_ADD_DESCRIPTOR", FW_CDEV_IOC_ADD_DESCRIPTOR, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_REMOVE_DESCRIPTOR", FW_CDEV_IOC_REMOVE_DESCRIPTOR, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_CREATE_ISO_CONTEXT", FW_CDEV_IOC_CREATE_ISO_CONTEXT, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_QUEUE_ISO", FW_CDEV_IOC_QUEUE_ISO, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_START_ISO", FW_CDEV_IOC_START_ISO, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_STOP_ISO", FW_CDEV_IOC_STOP_ISO, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_GET_CYCLE_TIMER", FW_CDEV_IOC_GET_CYCLE_TIMER, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_ALLOCATE_ISO_RESOURCE", FW_CDEV_IOC_ALLOCATE_ISO_RESOURCE, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_DEALLOCATE_ISO_RESOURCE", FW_CDEV_IOC_DEALLOCATE_ISO_RESOURCE, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_ALLOCATE_ISO_RESOURCE_ONCE", FW_CDEV_IOC_ALLOCATE_ISO_RESOURCE_ONCE, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_DEALLOCATE_ISO_RESOURCE_ONCE", FW_CDEV_IOC_DEALLOCATE_ISO_RESOURCE_ONCE, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_GET_SPEED", FW_CDEV_IOC_GET_SPEED, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_SEND_BROADCAST_REQUEST", FW_CDEV_IOC_SEND_BROADCAST_REQUEST, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_SEND_STREAM_PACKET", FW_CDEV_IOC_SEND_STREAM_PACKET, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_GET_CYCLE_TIMER2", FW_CDEV_IOC_GET_CYCLE_TIMER2, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_SEND_PHY_PACKET", FW_CDEV_IOC_SEND_PHY_PACKET, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_RECEIVE_PHY_PACKETS", FW_CDEV_IOC_RECEIVE_PHY_PACKETS, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_SET_ISO_CHANNELS", FW_CDEV_IOC_SET_ISO_CHANNELS, -1, -1 }, // linux/firewire-cdev.h
    { "FW_CDEV_IOC_FLUSH_ISO", FW_CDEV_IOC_FLUSH_ISO, -1, -1 }, // linux/firewire-cdev.h
    { "FDCLRPRM", FDCLRPRM, -1, -1 }, // linux/fd.h
    { "FDSETPRM", FDSETPRM, -1, -1 }, // linux/fd.h
    { "FDDEFPRM", FDDEFPRM, -1, -1 }, // linux/fd.h
    { "FDGETPRM", FDGETPRM, -1, -1 }, // linux/fd.h
    { "FDMSGON", FDMSGON, -1, -1 }, // linux/fd.h
    { "FDMSGOFF", FDMSGOFF, -1, -1 }, // linux/fd.h
    { "FDFMTBEG", FDFMTBEG, -1, -1 }, // linux/fd.h
    { "FDFMTTRK", FDFMTTRK, -1, -1 }, // linux/fd.h
    { "FDFMTEND", FDFMTEND, -1, -1 }, // linux/fd.h
    { "FDSETEMSGTRESH", FDSETEMSGTRESH, -1, -1 }, // linux/fd.h
    { "FDFLUSH", FDFLUSH, -1, -1 }, // linux/fd.h
    { "FDSETMAXERRS", FDSETMAXERRS, -1, -1 }, // linux/fd.h
    { "FDGETMAXERRS", FDGETMAXERRS, -1, -1 }, // linux/fd.h
    { "FDGETDRVTYP", FDGETDRVTYP, -1, -1 }, // linux/fd.h
    { "FDSETDRVPRM", FDSETDRVPRM, -1, -1 }, // linux/fd.h
    { "FDGETDRVPRM", FDGETDRVPRM, -1, -1 }, // linux/fd.h
    { "FDGETDRVSTAT", FDGETDRVSTAT, -1, -1 }, // linux/fd.h
    { "FDPOLLDRVSTAT", FDPOLLDRVSTAT, -1, -1 }, // linux/fd.h
    { "FDRESET", FDRESET, -1, -1 }, // linux/fd.h
    { "FDGETFDCSTAT", FDGETFDCSTAT, -1, -1 }, // linux/fd.h
    { "FDWERRORCLR", FDWERRORCLR, -1, -1 }, // linux/fd.h
    { "FDWERRORGET", FDWERRORGET, -1, -1 }, // linux/fd.h
    { "FDRAWCMD", FDRAWCMD, -1, -1 }, // linux/fd.h
    { "FDTWADDLE", FDTWADDLE, -1, -1 }, // linux/fd.h
    { "FDEJECT", FDEJECT, -1, -1 }, // linux/fd.h
    { "SIOCSIFATMTCP", SIOCSIFATMTCP, -1, -1 }, // linux/atm_tcp.h
    { "ATMTCP_CREATE", ATMTCP_CREATE, -1, -1 }, // linux/atm_tcp.h
    { "ATMTCP_REMOVE", ATMTCP_REMOVE, -1, -1 }, // linux/atm_tcp.h
    { "ENI_MEMDUMP", ENI_MEMDUMP, -1, -1 }, // linux/atm_eni.h
    { "ENI_SETMULT", ENI_SETMULT, -1, -1 }, // linux/atm_eni.h
    { "UVCIOC_CTRL_MAP", UVCIOC_CTRL_MAP, -1, -1 }, // linux/uvcvideo.h
    { "UVCIOC_CTRL_QUERY", UVCIOC_CTRL_QUERY, -1, -1 }, // linux/uvcvideo.h
    { "NVME_IOCTL_ID", NVME_IOCTL_ID, -1, -1 }, // linux/nvme.h
    { "NVME_IOCTL_ADMIN_CMD", NVME_IOCTL_ADMIN_CMD, -1, -1 }, // linux/nvme.h
    { "NVME_IOCTL_SUBMIT_IO", NVME_IOCTL_SUBMIT_IO, -1, -1 }, // linux/nvme.h
    { "HPET_IE_ON", HPET_IE_ON, -1, -1 }, // linux/hpet.h
    { "HPET_IE_OFF", HPET_IE_OFF, -1, -1 }, // linux/hpet.h
    { "HPET_INFO", HPET_INFO, -1, -1 }, // linux/hpet.h
    { "HPET_EPI", HPET_EPI, -1, -1 }, // linux/hpet.h
    { "HPET_DPI", HPET_DPI, -1, -1 }, // linux/hpet.h
    { "HPET_IRQFREQ", HPET_IRQFREQ, -1, -1 }, // linux/hpet.h
    { "SONYPI_IOCGBRT", SONYPI_IOCGBRT, -1, -1 }, // linux/sonypi.h
    { "SONYPI_IOCSBRT", SONYPI_IOCSBRT, -1, -1 }, // linux/sonypi.h
    { "SONYPI_IOCGBAT1CAP", SONYPI_IOCGBAT1CAP, -1, -1 }, // linux/sonypi.h
    { "SONYPI_IOCGBAT1REM", SONYPI_IOCGBAT1REM, -1, -1 }, // linux/sonypi.h
    { "SONYPI_IOCGBAT2CAP", SONYPI_IOCGBAT2CAP, -1, -1 }, // linux/sonypi.h
    { "SONYPI_IOCGBAT2REM", SONYPI_IOCGBAT2REM, -1, -1 }, // linux/sonypi.h
    { "SONYPI_IOCGBATFLAGS", SONYPI_IOCGBATFLAGS, -1, -1 }, // linux/sonypi.h
    { "SONYPI_IOCGBLUE", SONYPI_IOCGBLUE, -1, -1 }, // linux/sonypi.h
    { "SONYPI_IOCSBLUE", SONYPI_IOCSBLUE, -1, -1 }, // linux/sonypi.h
    { "SONYPI_IOCGFAN", SONYPI_IOCGFAN, -1, -1 }, // linux/sonypi.h
    { "SONYPI_IOCSFAN", SONYPI_IOCSFAN, -1, -1 }, // linux/sonypi.h
    { "SONYPI_IOCGTEMP", SONYPI_IOCGTEMP, -1, -1 }, // linux/sonypi.h
    { "UDF_GETEASIZE", UDF_GETEASIZE, -1, -1 }, // linux/udf_fs_i.h
    { "UDF_GETEABLOCK", UDF_GETEABLOCK, -1, -1 }, // linux/udf_fs_i.h
    { "UDF_GETVOLIDENT", UDF_GETVOLIDENT, -1, -1 }, // linux/udf_fs_i.h
    { "UDF_RELOCATE_BLOCKS", UDF_RELOCATE_BLOCKS, -1, -1 }, // linux/udf_fs_i.h
    { "IDT77105_GETSTAT", IDT77105_GETSTAT, -1, -1 }, // linux/atm_idt77105.h
    { "IDT77105_GETSTATZ", IDT77105_GETSTATZ, -1, -1 }, // linux/atm_idt77105.h
    { "SIOCSNETADDR", SIOCSNETADDR, -1, -1 }, // linux/dn.h
    { "SIOCGNETADDR", SIOCGNETADDR, -1, -1 }, // linux/dn.h
    { "OSIOCSNETADDR", OSIOCSNETADDR, -1, -1 }, // linux/dn.h
    { "OSIOCGNETADDR", OSIOCGNETADDR, -1, -1 }, // linux/dn.h
    { "UI_DEV_CREATE", UI_DEV_CREATE, -1, -1 }, // linux/uinput.h
    { "UI_DEV_DESTROY", UI_DEV_DESTROY, -1, -1 }, // linux/uinput.h
    { "UI_SET_EVBIT", UI_SET_EVBIT, -1, -1 }, // linux/uinput.h
    { "UI_SET_KEYBIT", UI_SET_KEYBIT, -1, -1 }, // linux/uinput.h
    { "UI_SET_RELBIT", UI_SET_RELBIT, -1, -1 }, // linux/uinput.h
    { "UI_SET_ABSBIT", UI_SET_ABSBIT, -1, -1 }, // linux/uinput.h
    { "UI_SET_MSCBIT", UI_SET_MSCBIT, -1, -1 }, // linux/uinput.h
    { "UI_SET_LEDBIT", UI_SET_LEDBIT, -1, -1 }, // linux/uinput.h
    { "UI_SET_SNDBIT", UI_SET_SNDBIT, -1, -1 }, // linux/uinput.h
    { "UI_SET_FFBIT", UI_SET_FFBIT, -1, -1 }, // linux/uinput.h
    { "UI_SET_PHYS", UI_SET_PHYS, -1, -1 }, // linux/uinput.h
    { "UI_SET_SWBIT", UI_SET_SWBIT, -1, -1 }, // linux/uinput.h
    { "UI_SET_PROPBIT", UI_SET_PROPBIT, -1, -1 }, // linux/uinput.h
    { "UI_BEGIN_FF_UPLOAD", UI_BEGIN_FF_UPLOAD, -1, -1 }, // linux/uinput.h
    { "UI_END_FF_UPLOAD", UI_END_FF_UPLOAD, -1, -1 }, // linux/uinput.h
    { "UI_BEGIN_FF_ERASE", UI_BEGIN_FF_ERASE, -1, -1 }, // linux/uinput.h
    { "UI_END_FF_ERASE", UI_END_FF_ERASE, -1, -1 }, // linux/uinput.h
    { "PMU_IOC_SLEEP", PMU_IOC_SLEEP, -1, -1 }, // linux/pmu.h
    { "PMU_IOC_GET_BACKLIGHT", PMU_IOC_GET_BACKLIGHT, -1, -1 }, // linux/pmu.h
    { "PMU_IOC_SET_BACKLIGHT", PMU_IOC_SET_BACKLIGHT, -1, -1 }, // linux/pmu.h
    { "PMU_IOC_GET_MODEL", PMU_IOC_GET_MODEL, -1, -1 }, // linux/pmu.h
    { "PMU_IOC_HAS_ADB", PMU_IOC_HAS_ADB, -1, -1 }, // linux/pmu.h
    { "PMU_IOC_CAN_SLEEP", PMU_IOC_CAN_SLEEP, -1, -1 }, // linux/pmu.h
    { "PMU_IOC_GRAB_BACKLIGHT", PMU_IOC_GRAB_BACKLIGHT, -1, -1 }, // linux/pmu.h
    { "BTRFS_IOC_SNAP_CREATE", BTRFS_IOC_SNAP_CREATE, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_DEFRAG", BTRFS_IOC_DEFRAG, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_RESIZE", BTRFS_IOC_RESIZE, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SCAN_DEV", BTRFS_IOC_SCAN_DEV, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_TRANS_START", BTRFS_IOC_TRANS_START, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_TRANS_END", BTRFS_IOC_TRANS_END, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SYNC", BTRFS_IOC_SYNC, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_CLONE", BTRFS_IOC_CLONE, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_ADD_DEV", BTRFS_IOC_ADD_DEV, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_RM_DEV", BTRFS_IOC_RM_DEV, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_BALANCE", BTRFS_IOC_BALANCE, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_CLONE_RANGE", BTRFS_IOC_CLONE_RANGE, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SUBVOL_CREATE", BTRFS_IOC_SUBVOL_CREATE, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SNAP_DESTROY", BTRFS_IOC_SNAP_DESTROY, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_TREE_SEARCH", BTRFS_IOC_TREE_SEARCH, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_INO_LOOKUP", BTRFS_IOC_INO_LOOKUP, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_DEFAULT_SUBVOL", BTRFS_IOC_DEFAULT_SUBVOL, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SPACE_INFO", BTRFS_IOC_SPACE_INFO, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_START_SYNC", BTRFS_IOC_START_SYNC, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_WAIT_SYNC", BTRFS_IOC_WAIT_SYNC, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SNAP_CREATE_V2", BTRFS_IOC_SNAP_CREATE_V2, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SUBVOL_CREATE_V2", BTRFS_IOC_SUBVOL_CREATE_V2, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SUBVOL_GETFLAGS", BTRFS_IOC_SUBVOL_GETFLAGS, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SUBVOL_SETFLAGS", BTRFS_IOC_SUBVOL_SETFLAGS, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SCRUB", BTRFS_IOC_SCRUB, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SCRUB_CANCEL", BTRFS_IOC_SCRUB_CANCEL, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SCRUB_PROGRESS", BTRFS_IOC_SCRUB_PROGRESS, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_DEV_INFO", BTRFS_IOC_DEV_INFO, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_FS_INFO", BTRFS_IOC_FS_INFO, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_BALANCE_V2", BTRFS_IOC_BALANCE_V2, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_BALANCE_CTL", BTRFS_IOC_BALANCE_CTL, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_BALANCE_PROGRESS", BTRFS_IOC_BALANCE_PROGRESS, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_INO_PATHS", BTRFS_IOC_INO_PATHS, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_LOGICAL_INO", BTRFS_IOC_LOGICAL_INO, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SET_RECEIVED_SUBVOL", BTRFS_IOC_SET_RECEIVED_SUBVOL, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_SEND", BTRFS_IOC_SEND, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_DEVICES_READY", BTRFS_IOC_DEVICES_READY, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_QUOTA_CTL", BTRFS_IOC_QUOTA_CTL, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_QGROUP_ASSIGN", BTRFS_IOC_QGROUP_ASSIGN, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_QGROUP_CREATE", BTRFS_IOC_QGROUP_CREATE, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_QGROUP_LIMIT", BTRFS_IOC_QGROUP_LIMIT, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_QUOTA_RESCAN", BTRFS_IOC_QUOTA_RESCAN, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_QUOTA_RESCAN_STATUS", BTRFS_IOC_QUOTA_RESCAN_STATUS, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_QUOTA_RESCAN_WAIT", BTRFS_IOC_QUOTA_RESCAN_WAIT, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_GET_DEV_STATS", BTRFS_IOC_GET_DEV_STATS, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_DEV_REPLACE", BTRFS_IOC_DEV_REPLACE, -1, -1 }, // linux/btrfs.h
    { "BTRFS_IOC_FILE_EXTENT_SAME", BTRFS_IOC_FILE_EXTENT_SAME, -1, -1 }, // linux/btrfs.h
    { "VIDIOC_QUERYCAP", VIDIOC_QUERYCAP, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_RESERVED", VIDIOC_RESERVED, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_ENUM_FMT", VIDIOC_ENUM_FMT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_FMT", VIDIOC_G_FMT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_FMT", VIDIOC_S_FMT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_REQBUFS", VIDIOC_REQBUFS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_QUERYBUF", VIDIOC_QUERYBUF, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_FBUF", VIDIOC_G_FBUF, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_FBUF", VIDIOC_S_FBUF, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_OVERLAY", VIDIOC_OVERLAY, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_QBUF", VIDIOC_QBUF, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_EXPBUF", VIDIOC_EXPBUF, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_DQBUF", VIDIOC_DQBUF, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_STREAMON", VIDIOC_STREAMON, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_STREAMOFF", VIDIOC_STREAMOFF, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_PARM", VIDIOC_G_PARM, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_PARM", VIDIOC_S_PARM, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_STD", VIDIOC_G_STD, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_STD", VIDIOC_S_STD, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_ENUMSTD", VIDIOC_ENUMSTD, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_ENUMINPUT", VIDIOC_ENUMINPUT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_CTRL", VIDIOC_G_CTRL, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_CTRL", VIDIOC_S_CTRL, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_TUNER", VIDIOC_G_TUNER, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_TUNER", VIDIOC_S_TUNER, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_AUDIO", VIDIOC_G_AUDIO, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_AUDIO", VIDIOC_S_AUDIO, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_QUERYCTRL", VIDIOC_QUERYCTRL, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_QUERYMENU", VIDIOC_QUERYMENU, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_INPUT", VIDIOC_G_INPUT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_INPUT", VIDIOC_S_INPUT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_OUTPUT", VIDIOC_G_OUTPUT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_OUTPUT", VIDIOC_S_OUTPUT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_ENUMOUTPUT", VIDIOC_ENUMOUTPUT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_AUDOUT", VIDIOC_G_AUDOUT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_AUDOUT", VIDIOC_S_AUDOUT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_MODULATOR", VIDIOC_G_MODULATOR, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_MODULATOR", VIDIOC_S_MODULATOR, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_FREQUENCY", VIDIOC_G_FREQUENCY, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_FREQUENCY", VIDIOC_S_FREQUENCY, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_CROPCAP", VIDIOC_CROPCAP, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_CROP", VIDIOC_G_CROP, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_CROP", VIDIOC_S_CROP, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_JPEGCOMP", VIDIOC_G_JPEGCOMP, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_JPEGCOMP", VIDIOC_S_JPEGCOMP, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_QUERYSTD", VIDIOC_QUERYSTD, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_TRY_FMT", VIDIOC_TRY_FMT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_ENUMAUDIO", VIDIOC_ENUMAUDIO, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_ENUMAUDOUT", VIDIOC_ENUMAUDOUT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_PRIORITY", VIDIOC_G_PRIORITY, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_PRIORITY", VIDIOC_S_PRIORITY, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_SLICED_VBI_CAP", VIDIOC_G_SLICED_VBI_CAP, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_LOG_STATUS", VIDIOC_LOG_STATUS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_EXT_CTRLS", VIDIOC_G_EXT_CTRLS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_EXT_CTRLS", VIDIOC_S_EXT_CTRLS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_TRY_EXT_CTRLS", VIDIOC_TRY_EXT_CTRLS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_ENUM_FRAMESIZES", VIDIOC_ENUM_FRAMESIZES, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_ENUM_FRAMEINTERVALS", VIDIOC_ENUM_FRAMEINTERVALS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_ENC_INDEX", VIDIOC_G_ENC_INDEX, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_ENCODER_CMD", VIDIOC_ENCODER_CMD, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_TRY_ENCODER_CMD", VIDIOC_TRY_ENCODER_CMD, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_DBG_S_REGISTER", VIDIOC_DBG_S_REGISTER, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_DBG_G_REGISTER", VIDIOC_DBG_G_REGISTER, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_HW_FREQ_SEEK", VIDIOC_S_HW_FREQ_SEEK, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_DV_TIMINGS", VIDIOC_S_DV_TIMINGS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_DV_TIMINGS", VIDIOC_G_DV_TIMINGS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_DQEVENT", VIDIOC_DQEVENT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_SUBSCRIBE_EVENT", VIDIOC_SUBSCRIBE_EVENT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_UNSUBSCRIBE_EVENT", VIDIOC_UNSUBSCRIBE_EVENT, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_CREATE_BUFS", VIDIOC_CREATE_BUFS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_PREPARE_BUF", VIDIOC_PREPARE_BUF, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_G_SELECTION", VIDIOC_G_SELECTION, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_S_SELECTION", VIDIOC_S_SELECTION, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_DECODER_CMD", VIDIOC_DECODER_CMD, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_TRY_DECODER_CMD", VIDIOC_TRY_DECODER_CMD, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_ENUM_DV_TIMINGS", VIDIOC_ENUM_DV_TIMINGS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_QUERY_DV_TIMINGS", VIDIOC_QUERY_DV_TIMINGS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_DV_TIMINGS_CAP", VIDIOC_DV_TIMINGS_CAP, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_ENUM_FREQ_BANDS", VIDIOC_ENUM_FREQ_BANDS, -1, -1 }, // linux/videodev2.h
    { "VIDIOC_DBG_G_CHIP_INFO", VIDIOC_DBG_G_CHIP_INFO, -1, -1 }, // linux/videodev2.h
    { "PERF_EVENT_IOC_PERIOD", PERF_EVENT_IOC_PERIOD, -1, -1 }, // linux/perf_event.h
    { "PERF_EVENT_IOC_SET_FILTER", PERF_EVENT_IOC_SET_FILTER, -1, -1 }, // linux/perf_event.h
    { "PERF_EVENT_IOC_ID", PERF_EVENT_IOC_ID, -1, -1 }, // linux/perf_event.h
    { "MMTIMER_GETOFFSET", MMTIMER_GETOFFSET, -1, -1 }, // linux/mmtimer.h
    { "MMTIMER_GETRES", MMTIMER_GETRES, -1, -1 }, // linux/mmtimer.h
    { "MMTIMER_GETFREQ", MMTIMER_GETFREQ, -1, -1 }, // linux/mmtimer.h
    { "MMTIMER_GETBITS", MMTIMER_GETBITS, -1, -1 }, // linux/mmtimer.h
    { "MMTIMER_MMAPAVAIL", MMTIMER_MMAPAVAIL, -1, -1 }, // linux/mmtimer.h
    { "MMTIMER_GETCOUNTER", MMTIMER_GETCOUNTER, -1, -1 }, // linux/mmtimer.h
    { "SIOCMKCLIP", SIOCMKCLIP, -1, -1 }, // linux/atmclip.h
    { "I2OGETIOPS", I2OGETIOPS, -1, -1 }, // linux/i2o-dev.h
    { "I2OHRTGET", I2OHRTGET, -1, -1 }, // linux/i2o-dev.h
    { "I2OLCTGET", I2OLCTGET, -1, -1 }, // linux/i2o-dev.h
    { "I2OPARMSET", I2OPARMSET, -1, -1 }, // linux/i2o-dev.h
    { "I2OPARMGET", I2OPARMGET, -1, -1 }, // linux/i2o-dev.h
    { "I2OSWDL", I2OSWDL, -1, -1 }, // linux/i2o-dev.h
    { "I2OSWUL", I2OSWUL, -1, -1 }, // linux/i2o-dev.h
    { "I2OSWDEL", I2OSWDEL, -1, -1 }, // linux/i2o-dev.h
    { "I2OVALIDATE", I2OVALIDATE, -1, -1 }, // linux/i2o-dev.h
    { "I2OHTML", I2OHTML, -1, -1 }, // linux/i2o-dev.h
    { "I2OEVTREG", I2OEVTREG, -1, -1 }, // linux/i2o-dev.h
    { "I2OEVTGET", I2OEVTGET, -1, -1 }, // linux/i2o-dev.h
    { "I2OPASSTHRU", I2OPASSTHRU, -1, -1 }, // linux/i2o-dev.h
    { "I2OPASSTHRU32", I2OPASSTHRU32, -1, -1 }, // linux/i2o-dev.h
    { "IIOCNETAIF", IIOCNETAIF, -1, -1 }, // linux/isdn.h
    { "IIOCNETDIF", IIOCNETDIF, -1, -1 }, // linux/isdn.h
    { "IIOCNETSCF", IIOCNETSCF, -1, -1 }, // linux/isdn.h
    { "IIOCNETGCF", IIOCNETGCF, -1, -1 }, // linux/isdn.h
    { "IIOCNETANM", IIOCNETANM, -1, -1 }, // linux/isdn.h
    { "IIOCNETDNM", IIOCNETDNM, -1, -1 }, // linux/isdn.h
    { "IIOCNETGNM", IIOCNETGNM, -1, -1 }, // linux/isdn.h
    { "IIOCGETSET", IIOCGETSET, -1, -1 }, // linux/isdn.h
    { "IIOCSETSET", IIOCSETSET, -1, -1 }, // linux/isdn.h
    { "IIOCSETVER", IIOCSETVER, -1, -1 }, // linux/isdn.h
    { "IIOCNETHUP", IIOCNETHUP, -1, -1 }, // linux/isdn.h
    { "IIOCSETGST", IIOCSETGST, -1, -1 }, // linux/isdn.h
    { "IIOCSETBRJ", IIOCSETBRJ, -1, -1 }, // linux/isdn.h
    { "IIOCSIGPRF", IIOCSIGPRF, -1, -1 }, // linux/isdn.h
    { "IIOCGETPRF", IIOCGETPRF, -1, -1 }, // linux/isdn.h
    { "IIOCSETPRF", IIOCSETPRF, -1, -1 }, // linux/isdn.h
    { "IIOCGETMAP", IIOCGETMAP, -1, -1 }, // linux/isdn.h
    { "IIOCSETMAP", IIOCSETMAP, -1, -1 }, // linux/isdn.h
    { "IIOCNETASL", IIOCNETASL, -1, -1 }, // linux/isdn.h
    { "IIOCNETDIL", IIOCNETDIL, -1, -1 }, // linux/isdn.h
    { "IIOCGETCPS", IIOCGETCPS, -1, -1 }, // linux/isdn.h
    { "IIOCGETDVR", IIOCGETDVR, -1, -1 }, // linux/isdn.h
    { "IIOCNETLCR", IIOCNETLCR, -1, -1 }, // linux/isdn.h
    { "IIOCNETDWRSET", IIOCNETDWRSET, -1, -1 }, // linux/isdn.h
    { "IIOCNETALN", IIOCNETALN, -1, -1 }, // linux/isdn.h
    { "IIOCNETDLN", IIOCNETDLN, -1, -1 }, // linux/isdn.h
    { "IIOCNETGPN", IIOCNETGPN, -1, -1 }, // linux/isdn.h
    { "IIOCDBGVAR", IIOCDBGVAR, -1, -1 }, // linux/isdn.h
    { "IIOCDRVCTL", IIOCDRVCTL, -1, -1 }, // linux/isdn.h
    { "SPIOCSTYPE", SPIOCSTYPE, -1, -1 }, // linux/serio.h
    { "GADGETFS_FIFO_STATUS", GADGETFS_FIFO_STATUS, -1, -1 }, // linux/usb/gadgetfs.h
    { "GADGETFS_FIFO_FLUSH", GADGETFS_FIFO_FLUSH, -1, -1 }, // linux/usb/gadgetfs.h
    { "GADGETFS_CLEAR_HALT", GADGETFS_CLEAR_HALT, -1, -1 }, // linux/usb/gadgetfs.h
    { "FUNCTIONFS_FIFO_STATUS", FUNCTIONFS_FIFO_STATUS, -1, -1 }, // linux/usb/functionfs.h
    { "FUNCTIONFS_FIFO_FLUSH", FUNCTIONFS_FIFO_FLUSH, -1, -1 }, // linux/usb/functionfs.h
    { "FUNCTIONFS_CLEAR_HALT", FUNCTIONFS_CLEAR_HALT, -1, -1 }, // linux/usb/functionfs.h
    { "FUNCTIONFS_INTERFACE_REVMAP", FUNCTIONFS_INTERFACE_REVMAP, -1, -1 }, // linux/usb/functionfs.h
    { "FUNCTIONFS_ENDPOINT_REVMAP", FUNCTIONFS_ENDPOINT_REVMAP, -1, -1 }, // linux/usb/functionfs.h
    { "GADGET_GET_PRINTER_STATUS", GADGET_GET_PRINTER_STATUS, -1, -1 }, // linux/usb/g_printer.h
    { "GADGET_SET_PRINTER_STATUS", GADGET_SET_PRINTER_STATUS, -1, -1 }, // linux/usb/g_printer.h
    { "USBTMC_IOCTL_INDICATOR_PULSE", USBTMC_IOCTL_INDICATOR_PULSE, -1, -1 }, // linux/usb/tmc.h
    { "USBTMC_IOCTL_CLEAR", USBTMC_IOCTL_CLEAR, -1, -1 }, // linux/usb/tmc.h
    { "USBTMC_IOCTL_ABORT_BULK_OUT", USBTMC_IOCTL_ABORT_BULK_OUT, -1, -1 }, // linux/usb/tmc.h
    { "USBTMC_IOCTL_ABORT_BULK_IN", USBTMC_IOCTL_ABORT_BULK_IN, -1, -1 }, // linux/usb/tmc.h
    { "USBTMC_IOCTL_CLEAR_OUT_HALT", USBTMC_IOCTL_CLEAR_OUT_HALT, -1, -1 }, // linux/usb/tmc.h
    { "USBTMC_IOCTL_CLEAR_IN_HALT", USBTMC_IOCTL_CLEAR_IN_HALT, -1, -1 }, // linux/usb/tmc.h
    { "PPSETMODE", PPSETMODE, -1, -1 }, // linux/ppdev.h
    { "PPRSTATUS", PPRSTATUS, -1, -1 }, // linux/ppdev.h
    { "PPRCONTROL", PPRCONTROL, -1, -1 }, // linux/ppdev.h
    { "PPWCONTROL", PPWCONTROL, -1, -1 }, // linux/ppdev.h
    { "PPFCONTROL", PPFCONTROL, -1, -1 }, // linux/ppdev.h
    { "PPRDATA", PPRDATA, -1, -1 }, // linux/ppdev.h
    { "PPWDATA", PPWDATA, -1, -1 }, // linux/ppdev.h
    { "PPCLAIM", PPCLAIM, -1, -1 }, // linux/ppdev.h
    { "PPRELEASE", PPRELEASE, -1, -1 }, // linux/ppdev.h
    { "PPYIELD", PPYIELD, -1, -1 }, // linux/ppdev.h
    { "PPEXCL", PPEXCL, -1, -1 }, // linux/ppdev.h
    { "PPDATADIR", PPDATADIR, -1, -1 }, // linux/ppdev.h
    { "PPNEGOT", PPNEGOT, -1, -1 }, // linux/ppdev.h
    { "PPWCTLONIRQ", PPWCTLONIRQ, -1, -1 }, // linux/ppdev.h
    { "PPCLRIRQ", PPCLRIRQ, -1, -1 }, // linux/ppdev.h
    { "PPSETPHASE", PPSETPHASE, -1, -1 }, // linux/ppdev.h
    { "PPGETTIME", PPGETTIME, -1, -1 }, // linux/ppdev.h
    { "PPSETTIME", PPSETTIME, -1, -1 }, // linux/ppdev.h
    { "PPGETMODES", PPGETMODES, -1, -1 }, // linux/ppdev.h
    { "PPGETMODE", PPGETMODE, -1, -1 }, // linux/ppdev.h
    { "PPGETPHASE", PPGETPHASE, -1, -1 }, // linux/ppdev.h
    { "PPGETFLAGS", PPGETFLAGS, -1, -1 }, // linux/ppdev.h
    { "PPSETFLAGS", PPSETFLAGS, -1, -1 }, // linux/ppdev.h
    { "SONET_GETSTAT", SONET_GETSTAT, -1, -1 }, // linux/sonet.h
    { "SONET_GETSTATZ", SONET_GETSTATZ, -1, -1 }, // linux/sonet.h
    { "SONET_SETDIAG", SONET_SETDIAG, -1, -1 }, // linux/sonet.h
    { "SONET_CLRDIAG", SONET_CLRDIAG, -1, -1 }, // linux/sonet.h
    { "SONET_GETDIAG", SONET_GETDIAG, -1, -1 }, // linux/sonet.h
    { "SONET_SETFRAMING", SONET_SETFRAMING, -1, -1 }, // linux/sonet.h
    { "SONET_GETFRAMING", SONET_GETFRAMING, -1, -1 }, // linux/sonet.h
    { "SONET_GETFRSENSE", SONET_GETFRSENSE, -1, -1 }, // linux/sonet.h
    { "ZATM_GETPOOL", ZATM_GETPOOL, -1, -1 }, // linux/atm_zatm.h
    { "ZATM_GETPOOLZ", ZATM_GETPOOLZ, -1, -1 }, // linux/atm_zatm.h
    { "ZATM_SETPOOL", ZATM_SETPOOL, -1, -1 }, // linux/atm_zatm.h
    { "NCP_IOC_NCPREQUEST", NCP_IOC_NCPREQUEST, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_GETMOUNTUID", NCP_IOC_GETMOUNTUID, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_GETMOUNTUID2", NCP_IOC_GETMOUNTUID2, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_CONN_LOGGED_IN", NCP_IOC_CONN_LOGGED_IN, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_GET_FS_INFO", NCP_IOC_GET_FS_INFO, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_GET_FS_INFO_V2", NCP_IOC_GET_FS_INFO_V2, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_SIGN_INIT", NCP_IOC_SIGN_INIT, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_SIGN_WANTED", NCP_IOC_SIGN_WANTED, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_SET_SIGN_WANTED", NCP_IOC_SET_SIGN_WANTED, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_LOCKUNLOCK", NCP_IOC_LOCKUNLOCK, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_GETROOT", NCP_IOC_GETROOT, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_SETROOT", NCP_IOC_SETROOT, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_GETOBJECTNAME", NCP_IOC_GETOBJECTNAME, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_SETOBJECTNAME", NCP_IOC_SETOBJECTNAME, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_GETPRIVATEDATA", NCP_IOC_GETPRIVATEDATA, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_SETPRIVATEDATA", NCP_IOC_SETPRIVATEDATA, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_GETCHARSETS", NCP_IOC_GETCHARSETS, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_SETCHARSETS", NCP_IOC_SETCHARSETS, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_GETDENTRYTTL", NCP_IOC_GETDENTRYTTL, -1, -1 }, // linux/ncp_fs.h
    { "NCP_IOC_SETDENTRYTTL", NCP_IOC_SETDENTRYTTL, -1, -1 }, // linux/ncp_fs.h
    { "SISFB_GET_INFO_SIZE", SISFB_GET_INFO_SIZE, -1, -1 }, // video/sisfb.h
    { "SISFB_GET_INFO", SISFB_GET_INFO, -1, -1 }, // video/sisfb.h
    { "SISFB_GET_VBRSTATUS", SISFB_GET_VBRSTATUS, -1, -1 }, // video/sisfb.h
    { "SISFB_GET_AUTOMAXIMIZE", SISFB_GET_AUTOMAXIMIZE, -1, -1 }, // video/sisfb.h
    { "SISFB_SET_AUTOMAXIMIZE", SISFB_SET_AUTOMAXIMIZE, -1, -1 }, // video/sisfb.h
    { "SISFB_GET_TVPOSOFFSET", SISFB_GET_TVPOSOFFSET, -1, -1 }, // video/sisfb.h
    { "SISFB_SET_TVPOSOFFSET", SISFB_SET_TVPOSOFFSET, -1, -1 }, // video/sisfb.h
    { "SISFB_COMMAND", SISFB_COMMAND, -1, -1 }, // video/sisfb.h
    { "SISFB_SET_LOCK", SISFB_SET_LOCK, -1, -1 }, // video/sisfb.h
    { "SISFB_GET_INFO_OLD", SISFB_GET_INFO_OLD, -1, -1 }, // video/sisfb.h
    { "SISFB_GET_VBRSTATUS_OLD", SISFB_GET_VBRSTATUS_OLD, -1, -1 }, // video/sisfb.h
    { "SISFB_GET_AUTOMAXIMIZE_OLD", SISFB_GET_AUTOMAXIMIZE_OLD, -1, -1 }, // video/sisfb.h
    { "SISFB_SET_AUTOMAXIMIZE_OLD", SISFB_SET_AUTOMAXIMIZE_OLD, -1, -1 }, // video/sisfb.h
    { "MTRRIOC_ADD_ENTRY", MTRRIOC_ADD_ENTRY, -1, -1 }, // x86_64-linux-gnu/asm/mtrr.h
    { "MTRRIOC_SET_ENTRY", MTRRIOC_SET_ENTRY, -1, -1 }, // x86_64-linux-gnu/asm/mtrr.h
    { "MTRRIOC_DEL_ENTRY", MTRRIOC_DEL_ENTRY, -1, -1 }, // x86_64-linux-gnu/asm/mtrr.h
    { "MTRRIOC_GET_ENTRY", MTRRIOC_GET_ENTRY, -1, -1 }, // x86_64-linux-gnu/asm/mtrr.h
    { "MTRRIOC_KILL_ENTRY", MTRRIOC_KILL_ENTRY, -1, -1 }, // x86_64-linux-gnu/asm/mtrr.h
    { "MTRRIOC_ADD_PAGE_ENTRY", MTRRIOC_ADD_PAGE_ENTRY, -1, -1 }, // x86_64-linux-gnu/asm/mtrr.h
    { "MTRRIOC_SET_PAGE_ENTRY", MTRRIOC_SET_PAGE_ENTRY, -1, -1 }, // x86_64-linux-gnu/asm/mtrr.h
    { "MTRRIOC_DEL_PAGE_ENTRY", MTRRIOC_DEL_PAGE_ENTRY, -1, -1 }, // x86_64-linux-gnu/asm/mtrr.h
    { "MTRRIOC_GET_PAGE_ENTRY", MTRRIOC_GET_PAGE_ENTRY, -1, -1 }, // x86_64-linux-gnu/asm/mtrr.h
    { "MTRRIOC_KILL_PAGE_ENTRY", MTRRIOC_KILL_PAGE_ENTRY, -1, -1 }, // x86_64-linux-gnu/asm/mtrr.h
    { "MCE_GET_RECORD_LEN", MCE_GET_RECORD_LEN, -1, -1 }, // x86_64-linux-gnu/asm/mce.h
    { "MCE_GET_LOG_LEN", MCE_GET_LOG_LEN, -1, -1 }, // x86_64-linux-gnu/asm/mce.h
    { "MCE_GETCLEAR_FLAGS", MCE_GETCLEAR_FLAGS, -1, -1 }, // x86_64-linux-gnu/asm/mce.h
    { NULL, 0 },
};
