/* File generated by gen_ioctls_list.sh      */
/* In case of problem, please read README.md */
#include "ioctls_list.h"
#include <stddef.h>

const struct ioctl_entry ioctls_list[] = {
    { NULL, 0 },
};
